// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v4.0.0
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:372


#include "CircleTrackTypeSupportC.h"
#include "tao/CDR.h"
#include "cstring"
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for CircleTrack::TrackDataTypeSupport.

CircleTrack::TrackDataTypeSupport_ptr
TAO::Objref_Traits<CircleTrack::TrackDataTypeSupport>::duplicate (CircleTrack::TrackDataTypeSupport_ptr p)
{
  return CircleTrack::TrackDataTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<CircleTrack::TrackDataTypeSupport>::release (CircleTrack::TrackDataTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

CircleTrack::TrackDataTypeSupport_ptr
TAO::Objref_Traits<CircleTrack::TrackDataTypeSupport>::nil ()
{
  return CircleTrack::TrackDataTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<CircleTrack::TrackDataTypeSupport>::marshal (const CircleTrack::TrackDataTypeSupport_ptr p,TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



CircleTrack::TrackDataTypeSupport::TrackDataTypeSupport ()
{}CircleTrack::TrackDataTypeSupport_ptr
CircleTrack::TrackDataTypeSupport::_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataTypeSupport::_duplicate (
      dynamic_cast<TrackDataTypeSupport_ptr> (_tao_objref));
}

CircleTrack::TrackDataTypeSupport_ptr
CircleTrack::TrackDataTypeSupport::_unchecked_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataTypeSupport::_duplicate (
      dynamic_cast<TrackDataTypeSupport_ptr> (_tao_objref));
}

CircleTrack::TrackDataTypeSupport_ptr
CircleTrack::TrackDataTypeSupport::_nil ()
{
  return nullptr;
}

CircleTrack::TrackDataTypeSupport_ptr
CircleTrack::TrackDataTypeSupport::_duplicate (TrackDataTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
CircleTrack::TrackDataTypeSupport::_tao_release (TrackDataTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
CircleTrack::TrackDataTypeSupport::_is_a (const char *value)
{
  if (
      std::strcmp (value, "IDL:DDS/TypeSupport:1.0") == 0 ||
      std::strcmp (value, "IDL:OpenDDS/DCPS/TypeSupport:1.0") == 0 ||
      std::strcmp (value, "IDL:CircleTrack/TrackDataTypeSupport:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/LocalObject:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
      )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* CircleTrack::TrackDataTypeSupport::_interface_repository_id () const
{
  return "IDL:CircleTrack/TrackDataTypeSupport:1.0";
}

::CORBA::Boolean
CircleTrack::TrackDataTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for CircleTrack::TrackDataDataWriter.

CircleTrack::TrackDataDataWriter_ptr
TAO::Objref_Traits<CircleTrack::TrackDataDataWriter>::duplicate (CircleTrack::TrackDataDataWriter_ptr p)
{
  return CircleTrack::TrackDataDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<CircleTrack::TrackDataDataWriter>::release (CircleTrack::TrackDataDataWriter_ptr p)
{
  ::CORBA::release (p);
}

CircleTrack::TrackDataDataWriter_ptr
TAO::Objref_Traits<CircleTrack::TrackDataDataWriter>::nil ()
{
  return CircleTrack::TrackDataDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<CircleTrack::TrackDataDataWriter>::marshal (const CircleTrack::TrackDataDataWriter_ptr p,TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



CircleTrack::TrackDataDataWriter::TrackDataDataWriter ()
{}CircleTrack::TrackDataDataWriter_ptr
CircleTrack::TrackDataDataWriter::_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataDataWriter::_duplicate (
      dynamic_cast<TrackDataDataWriter_ptr> (_tao_objref));
}

CircleTrack::TrackDataDataWriter_ptr
CircleTrack::TrackDataDataWriter::_unchecked_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataDataWriter::_duplicate (
      dynamic_cast<TrackDataDataWriter_ptr> (_tao_objref));
}

CircleTrack::TrackDataDataWriter_ptr
CircleTrack::TrackDataDataWriter::_nil ()
{
  return nullptr;
}

CircleTrack::TrackDataDataWriter_ptr
CircleTrack::TrackDataDataWriter::_duplicate (TrackDataDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
CircleTrack::TrackDataDataWriter::_tao_release (TrackDataDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
CircleTrack::TrackDataDataWriter::_is_a (const char *value)
{
  if (
      std::strcmp (value, "IDL:DDS/Entity:1.0") == 0 ||
      std::strcmp (value, "IDL:DDS/DataWriter:1.0") == 0 ||
      std::strcmp (value, "IDL:CircleTrack/TrackDataDataWriter:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/LocalObject:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
      )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* CircleTrack::TrackDataDataWriter::_interface_repository_id () const
{
  return "IDL:CircleTrack/TrackDataDataWriter:1.0";
}

::CORBA::Boolean
CircleTrack::TrackDataDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for CircleTrack::TrackDataDataReader.

CircleTrack::TrackDataDataReader_ptr
TAO::Objref_Traits<CircleTrack::TrackDataDataReader>::duplicate (CircleTrack::TrackDataDataReader_ptr p)
{
  return CircleTrack::TrackDataDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<CircleTrack::TrackDataDataReader>::release (CircleTrack::TrackDataDataReader_ptr p)
{
  ::CORBA::release (p);
}

CircleTrack::TrackDataDataReader_ptr
TAO::Objref_Traits<CircleTrack::TrackDataDataReader>::nil ()
{
  return CircleTrack::TrackDataDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<CircleTrack::TrackDataDataReader>::marshal (const CircleTrack::TrackDataDataReader_ptr p,TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



CircleTrack::TrackDataDataReader::TrackDataDataReader ()
{}CircleTrack::TrackDataDataReader_ptr
CircleTrack::TrackDataDataReader::_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataDataReader::_duplicate (
      dynamic_cast<TrackDataDataReader_ptr> (_tao_objref));
}

CircleTrack::TrackDataDataReader_ptr
CircleTrack::TrackDataDataReader::_unchecked_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataDataReader::_duplicate (
      dynamic_cast<TrackDataDataReader_ptr> (_tao_objref));
}

CircleTrack::TrackDataDataReader_ptr
CircleTrack::TrackDataDataReader::_nil ()
{
  return nullptr;
}

CircleTrack::TrackDataDataReader_ptr
CircleTrack::TrackDataDataReader::_duplicate (TrackDataDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
CircleTrack::TrackDataDataReader::_tao_release (TrackDataDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
CircleTrack::TrackDataDataReader::_is_a (const char *value)
{
  if (
      std::strcmp (value, "IDL:DDS/Entity:1.0") == 0 ||
      std::strcmp (value, "IDL:DDS/DataReader:1.0") == 0 ||
      std::strcmp (value, "IDL:OpenDDS/DCPS/DataReaderEx:1.0") == 0 ||
      std::strcmp (value, "IDL:CircleTrack/TrackDataDataReader:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/LocalObject:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
      )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* CircleTrack::TrackDataDataReader::_interface_repository_id () const
{
  return "IDL:CircleTrack/TrackDataDataReader:1.0";
}

::CORBA::Boolean
CircleTrack::TrackDataDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

