/* -*- C++ -*- */
/* Generated by /home/chandreu/opt/OpenDDS/OpenDDS-3.29.1/bin/opendds_idl version 3.29.1 (ACE version 8.0.0) running on input file SquareTrack.idl */
#ifndef OPENDDS_IDL_GENERATED_SQUARETRACKTYPESUPPORTIMPL_H_DADHSK
#define OPENDDS_IDL_GENERATED_SQUARETRACKTYPESUPPORTIMPL_H_DADHSK

#include <dds/Version.h>
#if !OPENDDS_VERSION_EXACTLY(3, 29, 1)
#  error "This file should be regenerated with opendds_idl"
#endif
#include <dds/DCPS/Definitions.h>

#include <dds/DdsDcpsC.h>

#include "SquareTrackC.h"
#include "SquareTrackTypeSupportC.h"
#include "dds/DCPS/Serializer.h"
#include "dds/DCPS/Service_Participant.h"
#include "dds/DCPS/TypeSupportImpl.h"
#include "dds/DCPS/TypeSupportImpl_T.h"
#include "dds/DCPS/Util.h"
#include "dds/DCPS/ValueDispatcher.h"
#include "dds/DCPS/ValueReader.h"
#include "dds/DCPS/ValueWriter.h"
#include "dds/DCPS/XTypes/DynamicDataAdapter.h"
#include "dds/DCPS/XTypes/TypeObject.h"


/* Begin MODULE: CORBA */


/* End MODULE: CORBA */


/* Begin MODULE: SquareTrack */



/* Begin STRUCT: TrackData */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

struct SquareTrack_TrackData_xtag {};
template<> const XTypes::TypeIdentifier& getMinimalTypeIdentifier<SquareTrack_TrackData_xtag>();

template<> const XTypes::TypeMap& getMinimalTypeMap<SquareTrack_TrackData_xtag>();

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

bool vread(OpenDDS::DCPS::ValueReader& value_reader,  ::SquareTrack::TrackData& value);

bool vread(OpenDDS::DCPS::ValueReader& value_reader, const NestedKeyOnly< ::SquareTrack::TrackData>& value);

bool vread(OpenDDS::DCPS::ValueReader& value_reader, const KeyOnly< ::SquareTrack::TrackData>& value);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

bool vwrite(OpenDDS::DCPS::ValueWriter& value_writer, const  ::SquareTrack::TrackData& value);

bool vwrite(OpenDDS::DCPS::ValueWriter& value_writer, const NestedKeyOnly<const  ::SquareTrack::TrackData>& value);

bool vwrite(OpenDDS::DCPS::ValueWriter& value_writer, const KeyOnly<const  ::SquareTrack::TrackData>& value);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

template<> void set_default( ::SquareTrack::TrackData& stru);

void serialized_size(const Encoding& encoding, size_t& size, const ::SquareTrack::TrackData& stru);

bool operator<<(Serializer& strm, const ::SquareTrack::TrackData& stru);

bool operator>>(Serializer& strm,  ::SquareTrack::TrackData& stru);

void serialized_size(const Encoding& encoding, size_t& size, const NestedKeyOnly<const ::SquareTrack::TrackData>& stru);

bool operator<<(Serializer& strm, const NestedKeyOnly<const ::SquareTrack::TrackData>& stru);

bool operator>>(Serializer& strm, const NestedKeyOnly< ::SquareTrack::TrackData>& stru);

void serialized_size(const Encoding& encoding, size_t& size, const KeyOnly<const ::SquareTrack::TrackData>& stru);

bool operator<<(Serializer& strm, const KeyOnly<const ::SquareTrack::TrackData>& stru);

bool operator>>(Serializer& strm, const KeyOnly< ::SquareTrack::TrackData>& stru);

template <>
struct MarshalTraits< ::SquareTrack::TrackData> {
  static void representations_allowed_by_type(DDS::DataRepresentationIdSeq& seq)
  {
    seq.length(4);
    seq[0] = DDS::XCDR_DATA_REPRESENTATION;
    seq[1] = DDS::XCDR2_DATA_REPRESENTATION;
    seq[2] = DDS::XML_DATA_REPRESENTATION;
    seq[3] = OpenDDS::DCPS::UNALIGNED_CDR_DATA_REPRESENTATION;
  }

  static SerializedSizeBound serialized_size_bound(const Encoding& encoding)
  {
    switch (encoding.kind()) {
    case Encoding::KIND_XCDR1:
      return SerializedSizeBound();
    case Encoding::KIND_XCDR2:
      return SerializedSizeBound();
    case Encoding::KIND_UNALIGNED_CDR:
      return SerializedSizeBound(28);
    default:
      OPENDDS_ASSERT(false);
      return SerializedSizeBound();
    }
  }

  static SerializedSizeBound key_only_serialized_size_bound(const Encoding& encoding)
  {
    switch (encoding.kind()) {
    case Encoding::KIND_XCDR1:
      return SerializedSizeBound();
    case Encoding::KIND_XCDR2:
      return SerializedSizeBound();
    case Encoding::KIND_UNALIGNED_CDR:
      return SerializedSizeBound(4);
    default:
      OPENDDS_ASSERT(false);
      return SerializedSizeBound();
    }
  }

  static bool to_message_block(ACE_Message_Block&, const  ::SquareTrack::TrackData&) { return false; }
  static bool from_message_block( ::SquareTrack::TrackData&, const ACE_Message_Block&) { return false; }
  static Extensibility extensibility() { return APPENDABLE; }
  static Extensibility max_extensibility_level() { return APPENDABLE; }
};
} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


namespace SquareTrack {
/// This structure supports use of std::map with one or more keys.
struct  TrackData_OpenDDS_KeyLessThan {
  bool operator()(const  ::SquareTrack::TrackData& v1, const  ::SquareTrack::TrackData& v2) const
  {
    using ::operator<; // TAO::String_Manager's operator< is in global NS
    if (v1.trackId < v2.trackId) return true;
    if (v2.trackId < v1.trackId) return false;
    return false;
  }
};
}

namespace SquareTrack {
class TrackDataTypeSupportImpl;
}
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS {
namespace DCPS {
template <>
struct DDSTraits< ::SquareTrack::TrackData> {
  typedef  ::SquareTrack::TrackData MessageType;
  typedef  ::SquareTrack::TrackDataSeq MessageSequenceType;
  typedef  ::SquareTrack::TrackDataSeq::PrivateMemberAccess MessageSequenceAdapterType;
  typedef  ::SquareTrack::TrackDataTypeSupport TypeSupportType;
  typedef  ::SquareTrack::TrackDataTypeSupportImpl TypeSupportImplType;
  typedef  ::SquareTrack::TrackDataDataWriter DataWriterType;
  typedef  ::SquareTrack::TrackDataDataReader DataReaderType;
  typedef  ::SquareTrack::TrackData_OpenDDS_KeyLessThan LessThanType;
  typedef OpenDDS::DCPS::KeyOnly<const  ::SquareTrack::TrackData> KeyOnlyType;
  typedef OpenDDS::DCPS::SquareTrack_TrackData_xtag XtagType;

  static const char* type_name() { return "SquareTrack::TrackData"; }
  static size_t key_count() { return 1; }
  static bool is_key(const char*);
};
} // namespace DCPS
} // namespace OpenDDS
OPENDDS_END_VERSIONED_NAMESPACE_DECL

namespace SquareTrack {
class  TrackDataTypeSupportImpl
  : public virtual OpenDDS::DCPS::TypeSupportImpl_T<TrackData>
  , public virtual OpenDDS::DCPS::ValueDispatcher_T<TrackData>
{
public:
  typedef TrackDataTypeSupport TypeSupportType;
  typedef TrackDataTypeSupport::_var_type _var_type;
  typedef TrackDataTypeSupport::_ptr_type _ptr_type;

  TrackDataTypeSupportImpl() {}
  virtual ~TrackDataTypeSupportImpl() {}

  virtual ::DDS::DataWriter_ptr create_datawriter();
  virtual ::DDS::DataReader_ptr create_datareader();
#ifndef OPENDDS_NO_MULTI_TOPIC
  virtual ::DDS::DataReader_ptr create_multitopic_datareader();
#endif /* !OPENDDS_NO_MULTI_TOPIC */
#ifndef OPENDDS_SAFETY_PROFILE
  TrackData create_sample(::DDS::DynamicData_ptr src);
#endif
#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
  virtual const OpenDDS::DCPS::MetaStruct& getMetaStructForType() const;
#endif /* !OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE */

  virtual const OpenDDS::XTypes::TypeIdentifier& getMinimalTypeIdentifier() const;
  virtual const OpenDDS::XTypes::TypeMap& getMinimalTypeMap() const;

  virtual const OpenDDS::XTypes::TypeIdentifier& getCompleteTypeIdentifier() const;
  virtual const OpenDDS::XTypes::TypeMap& getCompleteTypeMap() const;

  ::DDS::ReturnCode_t encode_to_string(const TrackData& in, CORBA::String_out out, OpenDDS::DCPS::RepresentationFormat* format);
  ::DDS::ReturnCode_t encode_to_bytes(const TrackData& in, ::DDS::OctetSeq_out out, OpenDDS::DCPS::RepresentationFormat* format);
  ::DDS::ReturnCode_t decode_from_string(const char* in, TrackData_out out, OpenDDS::DCPS::RepresentationFormat* format);
  ::DDS::ReturnCode_t decode_from_bytes(const ::DDS::OctetSeq& in, TrackData_out out, OpenDDS::DCPS::RepresentationFormat* format);

  static TrackDataTypeSupport::_ptr_type _narrow(CORBA::Object_ptr obj);
};

}
#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

class MetaStruct;

template<typename T>
const MetaStruct& getMetaStruct();

template<>
const MetaStruct& getMetaStruct< ::SquareTrack::TrackData>();
bool gen_skip_over(Serializer& ser,  ::SquareTrack::TrackData*);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif // ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace XTypes {

#ifndef OPENDDS_SAFETY_PROFILE
template <>
DDS::DynamicData_ptr get_dynamic_data_adapter< ::SquareTrack::TrackData,  ::SquareTrack::TrackData>(DDS::DynamicType_ptr type, const  ::SquareTrack::TrackData& value);

template <>
DDS::DynamicData_ptr get_dynamic_data_adapter< ::SquareTrack::TrackData,  ::SquareTrack::TrackData>(DDS::DynamicType_ptr type,  ::SquareTrack::TrackData& value);

template <>
const  ::SquareTrack::TrackData* get_dynamic_data_adapter_value< ::SquareTrack::TrackData,  ::SquareTrack::TrackData>(DDS::DynamicData_ptr dd);

#endif // ifndef OPENDDS_SAFETY_PROFILE

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


/* End STRUCT: TrackData */

/* End MODULE: SquareTrack */
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif /* OPENDDS_IDL_GENERATED_SQUARETRACKTYPESUPPORTIMPL_H_DADHSK */
