// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v4.0.0
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:372


#include "SquareTrackTypeSupportC.h"
#include "tao/CDR.h"
#include "cstring"

#if !defined (__ACE_INLINE__)
#include "SquareTrackTypeSupportC.inl"
#endif /* !defined INLINE */
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for SquareTrack::TrackDataTypeSupport.

SquareTrack::TrackDataTypeSupport_ptr
TAO::Objref_Traits<SquareTrack::TrackDataTypeSupport>::duplicate (SquareTrack::TrackDataTypeSupport_ptr p)
{
  return SquareTrack::TrackDataTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<SquareTrack::TrackDataTypeSupport>::release (SquareTrack::TrackDataTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

SquareTrack::TrackDataTypeSupport_ptr
TAO::Objref_Traits<SquareTrack::TrackDataTypeSupport>::nil ()
{
  return SquareTrack::TrackDataTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<SquareTrack::TrackDataTypeSupport>::marshal (const SquareTrack::TrackDataTypeSupport_ptr p,TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



SquareTrack::TrackDataTypeSupport::TrackDataTypeSupport ()
{}SquareTrack::TrackDataTypeSupport_ptr
SquareTrack::TrackDataTypeSupport::_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataTypeSupport::_duplicate (
      dynamic_cast<TrackDataTypeSupport_ptr> (_tao_objref));
}

SquareTrack::TrackDataTypeSupport_ptr
SquareTrack::TrackDataTypeSupport::_unchecked_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataTypeSupport::_duplicate (
      dynamic_cast<TrackDataTypeSupport_ptr> (_tao_objref));
}

SquareTrack::TrackDataTypeSupport_ptr
SquareTrack::TrackDataTypeSupport::_nil ()
{
  return nullptr;
}

SquareTrack::TrackDataTypeSupport_ptr
SquareTrack::TrackDataTypeSupport::_duplicate (TrackDataTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
SquareTrack::TrackDataTypeSupport::_tao_release (TrackDataTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
SquareTrack::TrackDataTypeSupport::_is_a (const char *value)
{
  if (
      std::strcmp (value, "IDL:DDS/TypeSupport:1.0") == 0 ||
      std::strcmp (value, "IDL:OpenDDS/DCPS/TypeSupport:1.0") == 0 ||
      std::strcmp (value, "IDL:SquareTrack/TrackDataTypeSupport:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/LocalObject:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
      )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* SquareTrack::TrackDataTypeSupport::_interface_repository_id () const
{
  return "IDL:SquareTrack/TrackDataTypeSupport:1.0";
}

::CORBA::Boolean
SquareTrack::TrackDataTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for SquareTrack::TrackDataDataWriter.

SquareTrack::TrackDataDataWriter_ptr
TAO::Objref_Traits<SquareTrack::TrackDataDataWriter>::duplicate (SquareTrack::TrackDataDataWriter_ptr p)
{
  return SquareTrack::TrackDataDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<SquareTrack::TrackDataDataWriter>::release (SquareTrack::TrackDataDataWriter_ptr p)
{
  ::CORBA::release (p);
}

SquareTrack::TrackDataDataWriter_ptr
TAO::Objref_Traits<SquareTrack::TrackDataDataWriter>::nil ()
{
  return SquareTrack::TrackDataDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<SquareTrack::TrackDataDataWriter>::marshal (const SquareTrack::TrackDataDataWriter_ptr p,TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



SquareTrack::TrackDataDataWriter::TrackDataDataWriter ()
{}SquareTrack::TrackDataDataWriter_ptr
SquareTrack::TrackDataDataWriter::_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataDataWriter::_duplicate (
      dynamic_cast<TrackDataDataWriter_ptr> (_tao_objref));
}

SquareTrack::TrackDataDataWriter_ptr
SquareTrack::TrackDataDataWriter::_unchecked_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataDataWriter::_duplicate (
      dynamic_cast<TrackDataDataWriter_ptr> (_tao_objref));
}

SquareTrack::TrackDataDataWriter_ptr
SquareTrack::TrackDataDataWriter::_nil ()
{
  return nullptr;
}

SquareTrack::TrackDataDataWriter_ptr
SquareTrack::TrackDataDataWriter::_duplicate (TrackDataDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
SquareTrack::TrackDataDataWriter::_tao_release (TrackDataDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
SquareTrack::TrackDataDataWriter::_is_a (const char *value)
{
  if (
      std::strcmp (value, "IDL:DDS/Entity:1.0") == 0 ||
      std::strcmp (value, "IDL:DDS/DataWriter:1.0") == 0 ||
      std::strcmp (value, "IDL:SquareTrack/TrackDataDataWriter:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/LocalObject:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
      )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* SquareTrack::TrackDataDataWriter::_interface_repository_id () const
{
  return "IDL:SquareTrack/TrackDataDataWriter:1.0";
}

::CORBA::Boolean
SquareTrack::TrackDataDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for SquareTrack::TrackDataDataReader.

SquareTrack::TrackDataDataReader_ptr
TAO::Objref_Traits<SquareTrack::TrackDataDataReader>::duplicate (SquareTrack::TrackDataDataReader_ptr p)
{
  return SquareTrack::TrackDataDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<SquareTrack::TrackDataDataReader>::release (SquareTrack::TrackDataDataReader_ptr p)
{
  ::CORBA::release (p);
}

SquareTrack::TrackDataDataReader_ptr
TAO::Objref_Traits<SquareTrack::TrackDataDataReader>::nil ()
{
  return SquareTrack::TrackDataDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<SquareTrack::TrackDataDataReader>::marshal (const SquareTrack::TrackDataDataReader_ptr p,TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



SquareTrack::TrackDataDataReader::TrackDataDataReader ()
{}SquareTrack::TrackDataDataReader_ptr
SquareTrack::TrackDataDataReader::_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataDataReader::_duplicate (
      dynamic_cast<TrackDataDataReader_ptr> (_tao_objref));
}

SquareTrack::TrackDataDataReader_ptr
SquareTrack::TrackDataDataReader::_unchecked_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataDataReader::_duplicate (
      dynamic_cast<TrackDataDataReader_ptr> (_tao_objref));
}

SquareTrack::TrackDataDataReader_ptr
SquareTrack::TrackDataDataReader::_nil ()
{
  return nullptr;
}

SquareTrack::TrackDataDataReader_ptr
SquareTrack::TrackDataDataReader::_duplicate (TrackDataDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
SquareTrack::TrackDataDataReader::_tao_release (TrackDataDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
SquareTrack::TrackDataDataReader::_is_a (const char *value)
{
  if (
      std::strcmp (value, "IDL:DDS/Entity:1.0") == 0 ||
      std::strcmp (value, "IDL:DDS/DataReader:1.0") == 0 ||
      std::strcmp (value, "IDL:OpenDDS/DCPS/DataReaderEx:1.0") == 0 ||
      std::strcmp (value, "IDL:SquareTrack/TrackDataDataReader:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/LocalObject:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
      )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* SquareTrack::TrackDataDataReader::_interface_repository_id () const
{
  return "IDL:SquareTrack/TrackDataDataReader:1.0";
}

::CORBA::Boolean
SquareTrack::TrackDataDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

