version: "3.9"

services:
  # 1. Backend C++ (Radar Engine)
  radar-be:
    build:
      context: ./be-stream-odds-cpp
      dockerfile: Dockerfile
    container_name: radar-backend-open
    privileged: true
    restart: unless-stopped
    networks:
      - radar-streaming-net
    volumes:
      - ./be-stream-odds-cpp/rtps.ini:/app/rtps.ini:ro
    environment:
      - LD_LIBRARY_PATH=/opt/OpenDDS/ACE_wrappers/lib:/opt/OpenDDS/lib
    command: ["./be-stream-odds-cpp", "-DCPSConfigFile", "/app/rtps.ini"]

  # 2. Gateway Standard OMG (DDS-WEB)
  radar-gateway:
    build:
      context: ./gateway-ddsweb
      dockerfile: Dockerfile
    container_name: radar-gateway-omg
    restart: unless-stopped
    networks:
      - radar-streaming-net
    ports:
      - "8080:8080"
    volumes:
      - ./be-stream-odds-cpp/rtps.ini:/app/rtps.ini:ro
    environment:
      - ACE_ROOT=/opt/OpenDDS/ACE_wrappers
      - TAO_ROOT=/opt/OpenDDS/ACE_wrappers/TAO
      - DDS_ROOT=/opt/OpenDDS
      # Path LD_LIBRARY_PATH harus mengarah ke lokasi library di dalam container
      - LD_LIBRARY_PATH=/opt/OpenDDS/ACE_wrappers/lib:/opt/OpenDDS/lib:/app/idl/RadarTrack:/app/idl/RadarCommand
    depends_on:
      - radar-be

  # 3. Frontend React (Radar Visualization)
  radar-fe:
    build:
      context: ./fe-webdds
      dockerfile: Dockerfile
    container_name: radar-frontend-omg
    restart: unless-stopped
    networks:
      - radar-streaming-net
    ports:
      - "3000:3000"
    environment:
      - VITE_DDS_GATEWAY_REST=http://localhost:8080/dds
      - VITE_DDS_GATEWAY_WS=ws://localhost:8080/dds
    volumes:
      - ./fe-webdds:/app
      - /app/node_modules
    depends_on:
      - radar-gateway

networks:
  radar-streaming-net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
