// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v4.0.0
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:148

#ifndef _TAO_IDL_TRIANGLETRACKTYPESUPPORTC_TQ7N1W_H_
#define _TAO_IDL_TRIANGLETRACKTYPESUPPORTC_TQ7N1W_H_


#include /**/ <ace/config-all.h>

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include <tao/ORB.h>
#include <tao/SystemException.h>
#include <tao/Basic_Types_IDLv4.h>
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

namespace CORBA
{
  using namespace IDLv4;
}

TAO_END_VERSIONED_NAMESPACE_DECL

#include <tao/ORB_Constants.h>
#include <dds/DCPS/ZeroCopyInfoSeq_T.h>
#include <dds/DCPS/ZeroCopySeq_T.h>
#include <tao/Object.h>
#include <tao/String_Manager_T.h>
#include <tao/Sequence_T.h>
#include <tao/Objref_VarOut_T.h>
#include <tao/Seq_Var_T.h>
#include <tao/Seq_Out_T.h>
#include <tao/Arg_Traits_T.h>
#include <tao/Basic_Arguments.h>
#include <tao/Special_Basic_Arguments.h>
#include <tao/Any_Insert_Policy_T.h>
#include <tao/Fixed_Size_Argument_T.h>
#include <tao/Var_Size_Argument_T.h>
#include "tao/Object_Argument_T.h"
#include "tao/UB_String_Arguments.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "TriangleTrackC.h"
#include "dds/DdsDcpsInfrastructureC.h"
#include "dds/DdsDcpsPublicationC.h"
#include "dds/DdsDcpsSubscriptionExtC.h"
#include "dds/DdsDcpsTopicC.h"
#include "dds/DdsDcpsTypeSupportExtC.h"
#include "dds/DdsDynamicDataC.h"

#if TAO_MAJOR_VERSION != 4 || TAO_MINOR_VERSION != 0 || TAO_MICRO_VERSION != 0
#error This file should be regenerated with TAO_IDL
#endif
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_module/module_ch.cpp:34

namespace TriangleTrack
{

  
  // TAO_IDL - Generated from
  // /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_sequence/sequence_ch.cpp:98

  

  typedef ::TAO::DCPS::ZeroCopyDataSeq< TriangleTrack::TrackData, DCPS_ZERO_COPY_SEQ_DEFAULT_SIZE> TrackDataSeq;
  
  // TAO_IDL - Generated from
  // /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_interface.cpp:742

  

#if !defined (_TRIANGLETRACK_TRACKDATATYPESUPPORT__VAR_OUT_CH_)
#define _TRIANGLETRACK_TRACKDATATYPESUPPORT__VAR_OUT_CH_

  class TrackDataTypeSupport;
  using TrackDataTypeSupport_ptr = TrackDataTypeSupport*;
  using TrackDataTypeSupport_var = TAO_Objref_Var_T<TrackDataTypeSupport>;
  using TrackDataTypeSupport_out = TAO_Objref_Out_T<TrackDataTypeSupport>;

#endif /* end #if !defined */

  
  // TAO_IDL - Generated from
  // /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:39

  

  class  TrackDataTypeSupport
    : public virtual ::OpenDDS::DCPS::TypeSupport
  
  {
  public:
    // TAO_IDL - Generated from
    // /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:297

    using _ptr_type = TrackDataTypeSupport_ptr;
    using _var_type = TrackDataTypeSupport_var;
    using _out_type = TrackDataTypeSupport_out;

    // The static operations.
    static TrackDataTypeSupport_ptr _duplicate (TrackDataTypeSupport_ptr obj);

    static void _tao_release (TrackDataTypeSupport_ptr obj);

    static TrackDataTypeSupport_ptr _narrow (::CORBA::Object_ptr obj);
    static TrackDataTypeSupport_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static TrackDataTypeSupport_ptr _nil ();

    virtual ::DDS::ReturnCode_t create_sample_rc (
      ::TriangleTrack::TrackData & dst,
      ::DDS::DynamicData_ptr src) = 0;

    virtual ::TriangleTrack::TrackData create_sample (
      ::DDS::DynamicData_ptr src) = 0;

    virtual ::DDS::ReturnCode_t create_dynamic_sample_rc (
      ::DDS::DynamicData_ptr & dst,
      const ::TriangleTrack::TrackData & src) = 0;

    virtual ::DDS::DynamicData_ptr create_dynamic_sample (
      const ::TriangleTrack::TrackData & src) = 0;

    virtual ::DDS::ReturnCode_t encode_to_string (
      const ::TriangleTrack::TrackData & sample,
      ::CORBA::String_out encoded,
      ::OpenDDS::DCPS::RepresentationFormat_ptr format) = 0;

    virtual ::DDS::ReturnCode_t encode_to_bytes (
      const ::TriangleTrack::TrackData & sample,
      ::DDS::OctetSeq_out encoded,
      ::OpenDDS::DCPS::RepresentationFormat_ptr format) = 0;

    virtual ::DDS::ReturnCode_t decode_from_string (
      const char * encoded,
      ::TriangleTrack::TrackData_out sample,
      ::OpenDDS::DCPS::RepresentationFormat_ptr format) = 0;

    virtual ::DDS::ReturnCode_t decode_from_bytes (
      const ::DDS::OctetSeq & encoded,
      ::TriangleTrack::TrackData_out sample,
      ::OpenDDS::DCPS::RepresentationFormat_ptr format) = 0;

    
    // TAO_IDL - Generated from
    // /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:135

    

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id () const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    TrackDataTypeSupport ();

    

    virtual ~TrackDataTypeSupport () = default;
  
  private:
    // Private and unimplemented for concrete interfaces.
    TrackDataTypeSupport (const TrackDataTypeSupport &) = delete;
    TrackDataTypeSupport (TrackDataTypeSupport &&) = delete;
    TrackDataTypeSupport &operator= (const TrackDataTypeSupport &) = delete;
    TrackDataTypeSupport &operator= (TrackDataTypeSupport &&) = delete;
  };
  // TAO_IDL - Generated from
  // /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_interface.cpp:742

  

#if !defined (_TRIANGLETRACK_TRACKDATADATAWRITER__VAR_OUT_CH_)
#define _TRIANGLETRACK_TRACKDATADATAWRITER__VAR_OUT_CH_

  class TrackDataDataWriter;
  using TrackDataDataWriter_ptr = TrackDataDataWriter*;
  using TrackDataDataWriter_var = TAO_Objref_Var_T<TrackDataDataWriter>;
  using TrackDataDataWriter_out = TAO_Objref_Out_T<TrackDataDataWriter>;

#endif /* end #if !defined */

  
  // TAO_IDL - Generated from
  // /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:39

  

  class  TrackDataDataWriter
    : public virtual ::DDS::DataWriter
  
  {
  public:
    // TAO_IDL - Generated from
    // /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:297

    using _ptr_type = TrackDataDataWriter_ptr;
    using _var_type = TrackDataDataWriter_var;
    using _out_type = TrackDataDataWriter_out;

    // The static operations.
    static TrackDataDataWriter_ptr _duplicate (TrackDataDataWriter_ptr obj);

    static void _tao_release (TrackDataDataWriter_ptr obj);

    static TrackDataDataWriter_ptr _narrow (::CORBA::Object_ptr obj);
    static TrackDataDataWriter_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static TrackDataDataWriter_ptr _nil ();

    virtual ::DDS::InstanceHandle_t register_instance (
      const ::TriangleTrack::TrackData & instance) = 0;

    virtual ::DDS::InstanceHandle_t register_instance_w_timestamp (
      const ::TriangleTrack::TrackData & instance,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance (
      const ::TriangleTrack::TrackData & instance,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance_w_timestamp (
      const ::TriangleTrack::TrackData & instance,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t write (
      const ::TriangleTrack::TrackData & instance_data,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t write_w_timestamp (
      const ::TriangleTrack::TrackData & instance_data,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t dispose (
      const ::TriangleTrack::TrackData & instance_data,
      ::DDS::InstanceHandle_t instance_handle) = 0;

    virtual ::DDS::ReturnCode_t dispose_w_timestamp (
      const ::TriangleTrack::TrackData & instance_data,
      ::DDS::InstanceHandle_t instance_handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::TriangleTrack::TrackData & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::TriangleTrack::TrackData & instance_data) = 0;

    
    // TAO_IDL - Generated from
    // /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:135

    

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id () const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    TrackDataDataWriter ();

    

    virtual ~TrackDataDataWriter () = default;
  
  private:
    // Private and unimplemented for concrete interfaces.
    TrackDataDataWriter (const TrackDataDataWriter &) = delete;
    TrackDataDataWriter (TrackDataDataWriter &&) = delete;
    TrackDataDataWriter &operator= (const TrackDataDataWriter &) = delete;
    TrackDataDataWriter &operator= (TrackDataDataWriter &&) = delete;
  };
  // TAO_IDL - Generated from
  // /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_interface.cpp:742

  

#if !defined (_TRIANGLETRACK_TRACKDATADATAREADER__VAR_OUT_CH_)
#define _TRIANGLETRACK_TRACKDATADATAREADER__VAR_OUT_CH_

  class TrackDataDataReader;
  using TrackDataDataReader_ptr = TrackDataDataReader*;
  using TrackDataDataReader_var = TAO_Objref_Var_T<TrackDataDataReader>;
  using TrackDataDataReader_out = TAO_Objref_Out_T<TrackDataDataReader>;

#endif /* end #if !defined */

  
  // TAO_IDL - Generated from
  // /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:39

  

  class  TrackDataDataReader
    : public virtual ::OpenDDS::DCPS::DataReaderEx
  
  {
  public:
    // TAO_IDL - Generated from
    // /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:297

    using _ptr_type = TrackDataDataReader_ptr;
    using _var_type = TrackDataDataReader_var;
    using _out_type = TrackDataDataReader_out;

    // The static operations.
    static TrackDataDataReader_ptr _duplicate (TrackDataDataReader_ptr obj);

    static void _tao_release (TrackDataDataReader_ptr obj);

    static TrackDataDataReader_ptr _narrow (::CORBA::Object_ptr obj);
    static TrackDataDataReader_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static TrackDataDataReader_ptr _nil ();

    virtual ::DDS::ReturnCode_t read (
      ::TriangleTrack::TrackDataSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take (
      ::TriangleTrack::TrackDataSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_w_condition (
      ::TriangleTrack::TrackDataSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_w_condition (
      ::TriangleTrack::TrackDataSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_sample (
      ::TriangleTrack::TrackData & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t take_next_sample (
      ::TriangleTrack::TrackData & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t read_instance (
      ::TriangleTrack::TrackDataSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_instance (
      ::TriangleTrack::TrackDataSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_instance_w_condition (
      ::TriangleTrack::TrackDataSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_instance_w_condition (
      ::TriangleTrack::TrackDataSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance (
      ::TriangleTrack::TrackDataSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance (
      ::TriangleTrack::TrackDataSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance_w_condition (
      ::TriangleTrack::TrackDataSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance_w_condition (
      ::TriangleTrack::TrackDataSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t return_loan (
      ::TriangleTrack::TrackDataSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::TriangleTrack::TrackData & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::TriangleTrack::TrackData & instance_data) = 0;

    
    // TAO_IDL - Generated from
    // /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:135

    

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id () const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    TrackDataDataReader ();

    

    virtual ~TrackDataDataReader () = default;
  
  private:
    // Private and unimplemented for concrete interfaces.
    TrackDataDataReader (const TrackDataDataReader &) = delete;
    TrackDataDataReader (TrackDataDataReader &&) = delete;
    TrackDataDataReader &operator= (const TrackDataDataReader &) = delete;
    TrackDataDataReader &operator= (TrackDataDataReader &&) = delete;
  };


// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_module/module_ch.cpp:62


} // module TriangleTrack
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:64



TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
}

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_traits.cpp:58



TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_TRIANGLETRACK_TRACKDATATYPESUPPORT__TRAITS_)
#define _TRIANGLETRACK_TRACKDATATYPESUPPORT__TRAITS_

  template<>
  struct  Objref_Traits< ::TriangleTrack::TrackDataTypeSupport>
  {
    static ::TriangleTrack::TrackDataTypeSupport_ptr duplicate (::TriangleTrack::TrackDataTypeSupport_ptr p);
    static void release (::TriangleTrack::TrackDataTypeSupport_ptr p);
    static ::TriangleTrack::TrackDataTypeSupport_ptr nil ();
    static ::CORBA::Boolean marshal (const ::TriangleTrack::TrackDataTypeSupport_ptr p,TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_TRIANGLETRACK_TRACKDATADATAWRITER__TRAITS_)
#define _TRIANGLETRACK_TRACKDATADATAWRITER__TRAITS_

  template<>
  struct  Objref_Traits< ::TriangleTrack::TrackDataDataWriter>
  {
    static ::TriangleTrack::TrackDataDataWriter_ptr duplicate (::TriangleTrack::TrackDataDataWriter_ptr p);
    static void release (::TriangleTrack::TrackDataDataWriter_ptr p);
    static ::TriangleTrack::TrackDataDataWriter_ptr nil ();
    static ::CORBA::Boolean marshal (const ::TriangleTrack::TrackDataDataWriter_ptr p,TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_TRIANGLETRACK_TRACKDATADATAREADER__TRAITS_)
#define _TRIANGLETRACK_TRACKDATADATAREADER__TRAITS_

  template<>
  struct  Objref_Traits< ::TriangleTrack::TrackDataDataReader>
  {
    static ::TriangleTrack::TrackDataDataReader_ptr duplicate (::TriangleTrack::TrackDataDataReader_ptr p);
    static void release (::TriangleTrack::TrackDataDataReader_ptr p);
    static ::TriangleTrack::TrackDataDataReader_ptr nil ();
    static ::CORBA::Boolean marshal (const ::TriangleTrack::TrackDataDataReader_ptr p,TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:1648

#endif /* ifndef */

