// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v4.0.0
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:372


#include "TriangleTrackTypeSupportC.h"
#include "tao/CDR.h"
#include "cstring"
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for TriangleTrack::TrackDataTypeSupport.

TriangleTrack::TrackDataTypeSupport_ptr
TAO::Objref_Traits<TriangleTrack::TrackDataTypeSupport>::duplicate (TriangleTrack::TrackDataTypeSupport_ptr p)
{
  return TriangleTrack::TrackDataTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<TriangleTrack::TrackDataTypeSupport>::release (TriangleTrack::TrackDataTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

TriangleTrack::TrackDataTypeSupport_ptr
TAO::Objref_Traits<TriangleTrack::TrackDataTypeSupport>::nil ()
{
  return TriangleTrack::TrackDataTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<TriangleTrack::TrackDataTypeSupport>::marshal (const TriangleTrack::TrackDataTypeSupport_ptr p,TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



TriangleTrack::TrackDataTypeSupport::TrackDataTypeSupport ()
{}TriangleTrack::TrackDataTypeSupport_ptr
TriangleTrack::TrackDataTypeSupport::_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataTypeSupport::_duplicate (
      dynamic_cast<TrackDataTypeSupport_ptr> (_tao_objref));
}

TriangleTrack::TrackDataTypeSupport_ptr
TriangleTrack::TrackDataTypeSupport::_unchecked_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataTypeSupport::_duplicate (
      dynamic_cast<TrackDataTypeSupport_ptr> (_tao_objref));
}

TriangleTrack::TrackDataTypeSupport_ptr
TriangleTrack::TrackDataTypeSupport::_nil ()
{
  return nullptr;
}

TriangleTrack::TrackDataTypeSupport_ptr
TriangleTrack::TrackDataTypeSupport::_duplicate (TrackDataTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
TriangleTrack::TrackDataTypeSupport::_tao_release (TrackDataTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
TriangleTrack::TrackDataTypeSupport::_is_a (const char *value)
{
  if (
      std::strcmp (value, "IDL:DDS/TypeSupport:1.0") == 0 ||
      std::strcmp (value, "IDL:OpenDDS/DCPS/TypeSupport:1.0") == 0 ||
      std::strcmp (value, "IDL:TriangleTrack/TrackDataTypeSupport:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/LocalObject:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
      )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* TriangleTrack::TrackDataTypeSupport::_interface_repository_id () const
{
  return "IDL:TriangleTrack/TrackDataTypeSupport:1.0";
}

::CORBA::Boolean
TriangleTrack::TrackDataTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for TriangleTrack::TrackDataDataWriter.

TriangleTrack::TrackDataDataWriter_ptr
TAO::Objref_Traits<TriangleTrack::TrackDataDataWriter>::duplicate (TriangleTrack::TrackDataDataWriter_ptr p)
{
  return TriangleTrack::TrackDataDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<TriangleTrack::TrackDataDataWriter>::release (TriangleTrack::TrackDataDataWriter_ptr p)
{
  ::CORBA::release (p);
}

TriangleTrack::TrackDataDataWriter_ptr
TAO::Objref_Traits<TriangleTrack::TrackDataDataWriter>::nil ()
{
  return TriangleTrack::TrackDataDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<TriangleTrack::TrackDataDataWriter>::marshal (const TriangleTrack::TrackDataDataWriter_ptr p,TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



TriangleTrack::TrackDataDataWriter::TrackDataDataWriter ()
{}TriangleTrack::TrackDataDataWriter_ptr
TriangleTrack::TrackDataDataWriter::_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataDataWriter::_duplicate (
      dynamic_cast<TrackDataDataWriter_ptr> (_tao_objref));
}

TriangleTrack::TrackDataDataWriter_ptr
TriangleTrack::TrackDataDataWriter::_unchecked_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataDataWriter::_duplicate (
      dynamic_cast<TrackDataDataWriter_ptr> (_tao_objref));
}

TriangleTrack::TrackDataDataWriter_ptr
TriangleTrack::TrackDataDataWriter::_nil ()
{
  return nullptr;
}

TriangleTrack::TrackDataDataWriter_ptr
TriangleTrack::TrackDataDataWriter::_duplicate (TrackDataDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
TriangleTrack::TrackDataDataWriter::_tao_release (TrackDataDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
TriangleTrack::TrackDataDataWriter::_is_a (const char *value)
{
  if (
      std::strcmp (value, "IDL:DDS/Entity:1.0") == 0 ||
      std::strcmp (value, "IDL:DDS/DataWriter:1.0") == 0 ||
      std::strcmp (value, "IDL:TriangleTrack/TrackDataDataWriter:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/LocalObject:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
      )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* TriangleTrack::TrackDataDataWriter::_interface_repository_id () const
{
  return "IDL:TriangleTrack/TrackDataDataWriter:1.0";
}

::CORBA::Boolean
TriangleTrack::TrackDataDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for TriangleTrack::TrackDataDataReader.

TriangleTrack::TrackDataDataReader_ptr
TAO::Objref_Traits<TriangleTrack::TrackDataDataReader>::duplicate (TriangleTrack::TrackDataDataReader_ptr p)
{
  return TriangleTrack::TrackDataDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<TriangleTrack::TrackDataDataReader>::release (TriangleTrack::TrackDataDataReader_ptr p)
{
  ::CORBA::release (p);
}

TriangleTrack::TrackDataDataReader_ptr
TAO::Objref_Traits<TriangleTrack::TrackDataDataReader>::nil ()
{
  return TriangleTrack::TrackDataDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<TriangleTrack::TrackDataDataReader>::marshal (const TriangleTrack::TrackDataDataReader_ptr p,TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



TriangleTrack::TrackDataDataReader::TrackDataDataReader ()
{}TriangleTrack::TrackDataDataReader_ptr
TriangleTrack::TrackDataDataReader::_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataDataReader::_duplicate (
      dynamic_cast<TrackDataDataReader_ptr> (_tao_objref));
}

TriangleTrack::TrackDataDataReader_ptr
TriangleTrack::TrackDataDataReader::_unchecked_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataDataReader::_duplicate (
      dynamic_cast<TrackDataDataReader_ptr> (_tao_objref));
}

TriangleTrack::TrackDataDataReader_ptr
TriangleTrack::TrackDataDataReader::_nil ()
{
  return nullptr;
}

TriangleTrack::TrackDataDataReader_ptr
TriangleTrack::TrackDataDataReader::_duplicate (TrackDataDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
TriangleTrack::TrackDataDataReader::_tao_release (TrackDataDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
TriangleTrack::TrackDataDataReader::_is_a (const char *value)
{
  if (
      std::strcmp (value, "IDL:DDS/Entity:1.0") == 0 ||
      std::strcmp (value, "IDL:DDS/DataReader:1.0") == 0 ||
      std::strcmp (value, "IDL:OpenDDS/DCPS/DataReaderEx:1.0") == 0 ||
      std::strcmp (value, "IDL:TriangleTrack/TrackDataDataReader:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/LocalObject:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
      )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* TriangleTrack::TrackDataDataReader::_interface_repository_id () const
{
  return "IDL:TriangleTrack/TrackDataDataReader:1.0";
}

::CORBA::Boolean
TriangleTrack::TrackDataDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

