// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v4.0.0
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:372


#include "TrapezoidTrackTypeSupportC.h"
#include "tao/CDR.h"
#include "cstring"
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for TrapezoidTrack::TrackDataTypeSupport.

TrapezoidTrack::TrackDataTypeSupport_ptr
TAO::Objref_Traits<TrapezoidTrack::TrackDataTypeSupport>::duplicate (TrapezoidTrack::TrackDataTypeSupport_ptr p)
{
  return TrapezoidTrack::TrackDataTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<TrapezoidTrack::TrackDataTypeSupport>::release (TrapezoidTrack::TrackDataTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

TrapezoidTrack::TrackDataTypeSupport_ptr
TAO::Objref_Traits<TrapezoidTrack::TrackDataTypeSupport>::nil ()
{
  return TrapezoidTrack::TrackDataTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<TrapezoidTrack::TrackDataTypeSupport>::marshal (const TrapezoidTrack::TrackDataTypeSupport_ptr p,TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



TrapezoidTrack::TrackDataTypeSupport::TrackDataTypeSupport ()
{}TrapezoidTrack::TrackDataTypeSupport_ptr
TrapezoidTrack::TrackDataTypeSupport::_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataTypeSupport::_duplicate (
      dynamic_cast<TrackDataTypeSupport_ptr> (_tao_objref));
}

TrapezoidTrack::TrackDataTypeSupport_ptr
TrapezoidTrack::TrackDataTypeSupport::_unchecked_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataTypeSupport::_duplicate (
      dynamic_cast<TrackDataTypeSupport_ptr> (_tao_objref));
}

TrapezoidTrack::TrackDataTypeSupport_ptr
TrapezoidTrack::TrackDataTypeSupport::_nil ()
{
  return nullptr;
}

TrapezoidTrack::TrackDataTypeSupport_ptr
TrapezoidTrack::TrackDataTypeSupport::_duplicate (TrackDataTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
TrapezoidTrack::TrackDataTypeSupport::_tao_release (TrackDataTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
TrapezoidTrack::TrackDataTypeSupport::_is_a (const char *value)
{
  if (
      std::strcmp (value, "IDL:DDS/TypeSupport:1.0") == 0 ||
      std::strcmp (value, "IDL:OpenDDS/DCPS/TypeSupport:1.0") == 0 ||
      std::strcmp (value, "IDL:TrapezoidTrack/TrackDataTypeSupport:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/LocalObject:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
      )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* TrapezoidTrack::TrackDataTypeSupport::_interface_repository_id () const
{
  return "IDL:TrapezoidTrack/TrackDataTypeSupport:1.0";
}

::CORBA::Boolean
TrapezoidTrack::TrackDataTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for TrapezoidTrack::TrackDataDataWriter.

TrapezoidTrack::TrackDataDataWriter_ptr
TAO::Objref_Traits<TrapezoidTrack::TrackDataDataWriter>::duplicate (TrapezoidTrack::TrackDataDataWriter_ptr p)
{
  return TrapezoidTrack::TrackDataDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<TrapezoidTrack::TrackDataDataWriter>::release (TrapezoidTrack::TrackDataDataWriter_ptr p)
{
  ::CORBA::release (p);
}

TrapezoidTrack::TrackDataDataWriter_ptr
TAO::Objref_Traits<TrapezoidTrack::TrackDataDataWriter>::nil ()
{
  return TrapezoidTrack::TrackDataDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<TrapezoidTrack::TrackDataDataWriter>::marshal (const TrapezoidTrack::TrackDataDataWriter_ptr p,TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



TrapezoidTrack::TrackDataDataWriter::TrackDataDataWriter ()
{}TrapezoidTrack::TrackDataDataWriter_ptr
TrapezoidTrack::TrackDataDataWriter::_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataDataWriter::_duplicate (
      dynamic_cast<TrackDataDataWriter_ptr> (_tao_objref));
}

TrapezoidTrack::TrackDataDataWriter_ptr
TrapezoidTrack::TrackDataDataWriter::_unchecked_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataDataWriter::_duplicate (
      dynamic_cast<TrackDataDataWriter_ptr> (_tao_objref));
}

TrapezoidTrack::TrackDataDataWriter_ptr
TrapezoidTrack::TrackDataDataWriter::_nil ()
{
  return nullptr;
}

TrapezoidTrack::TrackDataDataWriter_ptr
TrapezoidTrack::TrackDataDataWriter::_duplicate (TrackDataDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
TrapezoidTrack::TrackDataDataWriter::_tao_release (TrackDataDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
TrapezoidTrack::TrackDataDataWriter::_is_a (const char *value)
{
  if (
      std::strcmp (value, "IDL:DDS/Entity:1.0") == 0 ||
      std::strcmp (value, "IDL:DDS/DataWriter:1.0") == 0 ||
      std::strcmp (value, "IDL:TrapezoidTrack/TrackDataDataWriter:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/LocalObject:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
      )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* TrapezoidTrack::TrackDataDataWriter::_interface_repository_id () const
{
  return "IDL:TrapezoidTrack/TrackDataDataWriter:1.0";
}

::CORBA::Boolean
TrapezoidTrack::TrackDataDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for TrapezoidTrack::TrackDataDataReader.

TrapezoidTrack::TrackDataDataReader_ptr
TAO::Objref_Traits<TrapezoidTrack::TrackDataDataReader>::duplicate (TrapezoidTrack::TrackDataDataReader_ptr p)
{
  return TrapezoidTrack::TrackDataDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<TrapezoidTrack::TrackDataDataReader>::release (TrapezoidTrack::TrackDataDataReader_ptr p)
{
  ::CORBA::release (p);
}

TrapezoidTrack::TrackDataDataReader_ptr
TAO::Objref_Traits<TrapezoidTrack::TrackDataDataReader>::nil ()
{
  return TrapezoidTrack::TrackDataDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<TrapezoidTrack::TrackDataDataReader>::marshal (const TrapezoidTrack::TrackDataDataReader_ptr p,TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



TrapezoidTrack::TrackDataDataReader::TrackDataDataReader ()
{}TrapezoidTrack::TrackDataDataReader_ptr
TrapezoidTrack::TrackDataDataReader::_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataDataReader::_duplicate (
      dynamic_cast<TrackDataDataReader_ptr> (_tao_objref));
}

TrapezoidTrack::TrackDataDataReader_ptr
TrapezoidTrack::TrackDataDataReader::_unchecked_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataDataReader::_duplicate (
      dynamic_cast<TrackDataDataReader_ptr> (_tao_objref));
}

TrapezoidTrack::TrackDataDataReader_ptr
TrapezoidTrack::TrackDataDataReader::_nil ()
{
  return nullptr;
}

TrapezoidTrack::TrackDataDataReader_ptr
TrapezoidTrack::TrackDataDataReader::_duplicate (TrackDataDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
TrapezoidTrack::TrackDataDataReader::_tao_release (TrackDataDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
TrapezoidTrack::TrackDataDataReader::_is_a (const char *value)
{
  if (
      std::strcmp (value, "IDL:DDS/Entity:1.0") == 0 ||
      std::strcmp (value, "IDL:DDS/DataReader:1.0") == 0 ||
      std::strcmp (value, "IDL:OpenDDS/DCPS/DataReaderEx:1.0") == 0 ||
      std::strcmp (value, "IDL:TrapezoidTrack/TrackDataDataReader:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/LocalObject:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
      )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* TrapezoidTrack::TrackDataDataReader::_interface_repository_id () const
{
  return "IDL:TrapezoidTrack/TrackDataDataReader:1.0";
}

::CORBA::Boolean
TrapezoidTrack::TrackDataDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

