/* -*- C++ -*- */
/* Generated by opendds_idl version 3.29.1 (ACE version 8.0.0) running on input file RadarCommand.idl */
#ifndef OPENDDS_IDL_GENERATED_RADARCOMMANDTYPESUPPORTIMPL_H_LF240P
#define OPENDDS_IDL_GENERATED_RADARCOMMANDTYPESUPPORTIMPL_H_LF240P

#include <dds/Version.h>
#if !OPENDDS_VERSION_EXACTLY(3, 29, 1)
#  error "This file should be regenerated with opendds_idl"
#endif
#include <dds/DCPS/Definitions.h>

#include <dds/DdsDcpsC.h>

#include "RadarCommandC.h"
#include "RadarCommandTypeSupportC.h"
#include "dds/DCPS/Serializer.h"
#include "dds/DCPS/Service_Participant.h"
#include "dds/DCPS/TypeSupportImpl.h"
#include "dds/DCPS/TypeSupportImpl_T.h"
#include "dds/DCPS/Util.h"
#include "dds/DCPS/ValueDispatcher.h"
#include "dds/DCPS/ValueReader.h"
#include "dds/DCPS/ValueWriter.h"
#include "dds/DCPS/XTypes/DynamicDataAdapter.h"
#include "dds/DCPS/XTypes/TypeObject.h"


/* Begin MODULE: CORBA */


/* End MODULE: CORBA */


/* Begin MODULE: RadarCommand */



/* Begin STRUCT: Command */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

struct RadarCommand_Command_xtag {};
template<> const XTypes::TypeIdentifier& getMinimalTypeIdentifier<RadarCommand_Command_xtag>();

template<> const XTypes::TypeMap& getMinimalTypeMap<RadarCommand_Command_xtag>();

template<> const XTypes::TypeIdentifier& getCompleteTypeIdentifier<RadarCommand_Command_xtag>();

template<> const XTypes::TypeMap& getCompleteTypeMap<RadarCommand_Command_xtag>();

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

bool vread(OpenDDS::DCPS::ValueReader& value_reader,  ::RadarCommand::Command& value);

bool vread(OpenDDS::DCPS::ValueReader& value_reader, const NestedKeyOnly< ::RadarCommand::Command>& value);

bool vread(OpenDDS::DCPS::ValueReader& value_reader, const KeyOnly< ::RadarCommand::Command>& value);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

bool vwrite(OpenDDS::DCPS::ValueWriter& value_writer, const  ::RadarCommand::Command& value);

bool vwrite(OpenDDS::DCPS::ValueWriter& value_writer, const NestedKeyOnly<const  ::RadarCommand::Command>& value);

bool vwrite(OpenDDS::DCPS::ValueWriter& value_writer, const KeyOnly<const  ::RadarCommand::Command>& value);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

template<> void set_default( ::RadarCommand::Command& stru);

void serialized_size(const Encoding& encoding, size_t& size, const ::RadarCommand::Command& stru);

bool operator<<(Serializer& strm, const ::RadarCommand::Command& stru);

bool operator>>(Serializer& strm,  ::RadarCommand::Command& stru);

void serialized_size(const Encoding& encoding, size_t& size, const NestedKeyOnly<const ::RadarCommand::Command>& stru);

bool operator<<(Serializer& strm, const NestedKeyOnly<const ::RadarCommand::Command>& stru);

bool operator>>(Serializer& strm, const NestedKeyOnly< ::RadarCommand::Command>& stru);

void serialized_size(const Encoding& encoding, size_t& size, const KeyOnly<const ::RadarCommand::Command>& stru);

bool operator<<(Serializer& strm, const KeyOnly<const ::RadarCommand::Command>& stru);

bool operator>>(Serializer& strm, const KeyOnly< ::RadarCommand::Command>& stru);

template <>
struct MarshalTraits< ::RadarCommand::Command> {
  static void representations_allowed_by_type(DDS::DataRepresentationIdSeq& seq)
  {
    seq.length(4);
    seq[0] = DDS::XCDR_DATA_REPRESENTATION;
    seq[1] = DDS::XCDR2_DATA_REPRESENTATION;
    seq[2] = DDS::XML_DATA_REPRESENTATION;
    seq[3] = OpenDDS::DCPS::UNALIGNED_CDR_DATA_REPRESENTATION;
  }

  static SerializedSizeBound serialized_size_bound(const Encoding& encoding)
  {
    switch (encoding.kind()) {
    case Encoding::KIND_XCDR1:
      return SerializedSizeBound();
    case Encoding::KIND_XCDR2:
      return SerializedSizeBound();
    case Encoding::KIND_UNALIGNED_CDR:
      return SerializedSizeBound();
    default:
      OPENDDS_ASSERT(false);
      return SerializedSizeBound();
    }
  }

  static SerializedSizeBound key_only_serialized_size_bound(const Encoding& encoding)
  {
    switch (encoding.kind()) {
    case Encoding::KIND_XCDR1:
      return SerializedSizeBound();
    case Encoding::KIND_XCDR2:
      return SerializedSizeBound();
    case Encoding::KIND_UNALIGNED_CDR:
      return SerializedSizeBound(0);
    default:
      OPENDDS_ASSERT(false);
      return SerializedSizeBound();
    }
  }

  static bool to_message_block(ACE_Message_Block&, const  ::RadarCommand::Command&) { return false; }
  static bool from_message_block( ::RadarCommand::Command&, const ACE_Message_Block&) { return false; }
  static Extensibility extensibility() { return APPENDABLE; }
  static Extensibility max_extensibility_level() { return APPENDABLE; }
};
} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


namespace RadarCommand {
/// This structure supports use of std::map with one or more keys.
struct  Command_OpenDDS_KeyLessThan {
  bool operator()(const  ::RadarCommand::Command&, const  ::RadarCommand::Command&) const
  {
    // With no keys, return false to allow use of
    // map with just one entry
    return false;
  }
};
}

namespace RadarCommand {
class CommandTypeSupportImpl;
}
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS {
namespace DCPS {
template <>
struct DDSTraits< ::RadarCommand::Command> {
  typedef  ::RadarCommand::Command MessageType;
  typedef  ::RadarCommand::CommandSeq MessageSequenceType;
  typedef  ::RadarCommand::CommandSeq::PrivateMemberAccess MessageSequenceAdapterType;
  typedef  ::RadarCommand::CommandTypeSupport TypeSupportType;
  typedef  ::RadarCommand::CommandTypeSupportImpl TypeSupportImplType;
  typedef  ::RadarCommand::CommandDataWriter DataWriterType;
  typedef  ::RadarCommand::CommandDataReader DataReaderType;
  typedef  ::RadarCommand::Command_OpenDDS_KeyLessThan LessThanType;
  typedef OpenDDS::DCPS::KeyOnly<const  ::RadarCommand::Command> KeyOnlyType;
  typedef OpenDDS::DCPS::RadarCommand_Command_xtag XtagType;

  static const char* type_name() { return "RadarCommand::Command"; }
  static size_t key_count() { return 0; }
  static bool is_key(const char*);
};
} // namespace DCPS
} // namespace OpenDDS
OPENDDS_END_VERSIONED_NAMESPACE_DECL

namespace RadarCommand {
class  CommandTypeSupportImpl
  : public virtual OpenDDS::DCPS::TypeSupportImpl_T<Command>
  , public virtual OpenDDS::DCPS::ValueDispatcher_T<Command>
{
public:
  typedef CommandTypeSupport TypeSupportType;
  typedef CommandTypeSupport::_var_type _var_type;
  typedef CommandTypeSupport::_ptr_type _ptr_type;

  CommandTypeSupportImpl() {}
  virtual ~CommandTypeSupportImpl() {}

  virtual ::DDS::DataWriter_ptr create_datawriter();
  virtual ::DDS::DataReader_ptr create_datareader();
#ifndef OPENDDS_NO_MULTI_TOPIC
  virtual ::DDS::DataReader_ptr create_multitopic_datareader();
#endif /* !OPENDDS_NO_MULTI_TOPIC */
#ifndef OPENDDS_SAFETY_PROFILE
  Command* create_sample(::DDS::DynamicData_ptr src);
#endif
#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
  virtual const OpenDDS::DCPS::MetaStruct& getMetaStructForType() const;
#endif /* !OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE */

  virtual const OpenDDS::XTypes::TypeIdentifier& getMinimalTypeIdentifier() const;
  virtual const OpenDDS::XTypes::TypeMap& getMinimalTypeMap() const;

  virtual const OpenDDS::XTypes::TypeIdentifier& getCompleteTypeIdentifier() const;
  virtual const OpenDDS::XTypes::TypeMap& getCompleteTypeMap() const;

  ::DDS::ReturnCode_t encode_to_string(const Command& in, CORBA::String_out out, OpenDDS::DCPS::RepresentationFormat* format);
  ::DDS::ReturnCode_t encode_to_bytes(const Command& in, ::DDS::OctetSeq_out out, OpenDDS::DCPS::RepresentationFormat* format);
  ::DDS::ReturnCode_t decode_from_string(const char* in, Command_out out, OpenDDS::DCPS::RepresentationFormat* format);
  ::DDS::ReturnCode_t decode_from_bytes(const ::DDS::OctetSeq& in, Command_out out, OpenDDS::DCPS::RepresentationFormat* format);

  static CommandTypeSupport::_ptr_type _narrow(CORBA::Object_ptr obj);
};

}
#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

class MetaStruct;

template<typename T>
const MetaStruct& getMetaStruct();

template<>
const MetaStruct& getMetaStruct< ::RadarCommand::Command>();
bool gen_skip_over(Serializer& ser,  ::RadarCommand::Command*);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif // ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace XTypes {

#ifndef OPENDDS_SAFETY_PROFILE
template <>
DDS::DynamicData_ptr get_dynamic_data_adapter< ::RadarCommand::Command,  ::RadarCommand::Command>(DDS::DynamicType_ptr type, const  ::RadarCommand::Command& value);

template <>
DDS::DynamicData_ptr get_dynamic_data_adapter< ::RadarCommand::Command,  ::RadarCommand::Command>(DDS::DynamicType_ptr type,  ::RadarCommand::Command& value);

template <>
const  ::RadarCommand::Command* get_dynamic_data_adapter_value< ::RadarCommand::Command,  ::RadarCommand::Command>(DDS::DynamicData_ptr dd);

#endif // ifndef OPENDDS_SAFETY_PROFILE

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


/* End STRUCT: Command */

/* End MODULE: RadarCommand */
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif /* OPENDDS_IDL_GENERATED_RADARCOMMANDTYPESUPPORTIMPL_H_LF240P */
