// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v4.0.0
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:372


#include "ParallelogramTrackTypeSupportC.h"
#include "tao/CDR.h"
#include "cstring"
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for ParallelogramTrack::TrackDataTypeSupport.

ParallelogramTrack::TrackDataTypeSupport_ptr
TAO::Objref_Traits<ParallelogramTrack::TrackDataTypeSupport>::duplicate (ParallelogramTrack::TrackDataTypeSupport_ptr p)
{
  return ParallelogramTrack::TrackDataTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<ParallelogramTrack::TrackDataTypeSupport>::release (ParallelogramTrack::TrackDataTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

ParallelogramTrack::TrackDataTypeSupport_ptr
TAO::Objref_Traits<ParallelogramTrack::TrackDataTypeSupport>::nil ()
{
  return ParallelogramTrack::TrackDataTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<ParallelogramTrack::TrackDataTypeSupport>::marshal (const ParallelogramTrack::TrackDataTypeSupport_ptr p,TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



ParallelogramTrack::TrackDataTypeSupport::TrackDataTypeSupport ()
{}ParallelogramTrack::TrackDataTypeSupport_ptr
ParallelogramTrack::TrackDataTypeSupport::_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataTypeSupport::_duplicate (
      dynamic_cast<TrackDataTypeSupport_ptr> (_tao_objref));
}

ParallelogramTrack::TrackDataTypeSupport_ptr
ParallelogramTrack::TrackDataTypeSupport::_unchecked_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataTypeSupport::_duplicate (
      dynamic_cast<TrackDataTypeSupport_ptr> (_tao_objref));
}

ParallelogramTrack::TrackDataTypeSupport_ptr
ParallelogramTrack::TrackDataTypeSupport::_nil ()
{
  return nullptr;
}

ParallelogramTrack::TrackDataTypeSupport_ptr
ParallelogramTrack::TrackDataTypeSupport::_duplicate (TrackDataTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
ParallelogramTrack::TrackDataTypeSupport::_tao_release (TrackDataTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
ParallelogramTrack::TrackDataTypeSupport::_is_a (const char *value)
{
  if (
      std::strcmp (value, "IDL:DDS/TypeSupport:1.0") == 0 ||
      std::strcmp (value, "IDL:OpenDDS/DCPS/TypeSupport:1.0") == 0 ||
      std::strcmp (value, "IDL:ParallelogramTrack/TrackDataTypeSupport:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/LocalObject:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
      )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* ParallelogramTrack::TrackDataTypeSupport::_interface_repository_id () const
{
  return "IDL:ParallelogramTrack/TrackDataTypeSupport:1.0";
}

::CORBA::Boolean
ParallelogramTrack::TrackDataTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for ParallelogramTrack::TrackDataDataWriter.

ParallelogramTrack::TrackDataDataWriter_ptr
TAO::Objref_Traits<ParallelogramTrack::TrackDataDataWriter>::duplicate (ParallelogramTrack::TrackDataDataWriter_ptr p)
{
  return ParallelogramTrack::TrackDataDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<ParallelogramTrack::TrackDataDataWriter>::release (ParallelogramTrack::TrackDataDataWriter_ptr p)
{
  ::CORBA::release (p);
}

ParallelogramTrack::TrackDataDataWriter_ptr
TAO::Objref_Traits<ParallelogramTrack::TrackDataDataWriter>::nil ()
{
  return ParallelogramTrack::TrackDataDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<ParallelogramTrack::TrackDataDataWriter>::marshal (const ParallelogramTrack::TrackDataDataWriter_ptr p,TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



ParallelogramTrack::TrackDataDataWriter::TrackDataDataWriter ()
{}ParallelogramTrack::TrackDataDataWriter_ptr
ParallelogramTrack::TrackDataDataWriter::_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataDataWriter::_duplicate (
      dynamic_cast<TrackDataDataWriter_ptr> (_tao_objref));
}

ParallelogramTrack::TrackDataDataWriter_ptr
ParallelogramTrack::TrackDataDataWriter::_unchecked_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataDataWriter::_duplicate (
      dynamic_cast<TrackDataDataWriter_ptr> (_tao_objref));
}

ParallelogramTrack::TrackDataDataWriter_ptr
ParallelogramTrack::TrackDataDataWriter::_nil ()
{
  return nullptr;
}

ParallelogramTrack::TrackDataDataWriter_ptr
ParallelogramTrack::TrackDataDataWriter::_duplicate (TrackDataDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
ParallelogramTrack::TrackDataDataWriter::_tao_release (TrackDataDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
ParallelogramTrack::TrackDataDataWriter::_is_a (const char *value)
{
  if (
      std::strcmp (value, "IDL:DDS/Entity:1.0") == 0 ||
      std::strcmp (value, "IDL:DDS/DataWriter:1.0") == 0 ||
      std::strcmp (value, "IDL:ParallelogramTrack/TrackDataDataWriter:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/LocalObject:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
      )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* ParallelogramTrack::TrackDataDataWriter::_interface_repository_id () const
{
  return "IDL:ParallelogramTrack/TrackDataDataWriter:1.0";
}

::CORBA::Boolean
ParallelogramTrack::TrackDataDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for ParallelogramTrack::TrackDataDataReader.

ParallelogramTrack::TrackDataDataReader_ptr
TAO::Objref_Traits<ParallelogramTrack::TrackDataDataReader>::duplicate (ParallelogramTrack::TrackDataDataReader_ptr p)
{
  return ParallelogramTrack::TrackDataDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<ParallelogramTrack::TrackDataDataReader>::release (ParallelogramTrack::TrackDataDataReader_ptr p)
{
  ::CORBA::release (p);
}

ParallelogramTrack::TrackDataDataReader_ptr
TAO::Objref_Traits<ParallelogramTrack::TrackDataDataReader>::nil ()
{
  return ParallelogramTrack::TrackDataDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<ParallelogramTrack::TrackDataDataReader>::marshal (const ParallelogramTrack::TrackDataDataReader_ptr p,TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



ParallelogramTrack::TrackDataDataReader::TrackDataDataReader ()
{}ParallelogramTrack::TrackDataDataReader_ptr
ParallelogramTrack::TrackDataDataReader::_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataDataReader::_duplicate (
      dynamic_cast<TrackDataDataReader_ptr> (_tao_objref));
}

ParallelogramTrack::TrackDataDataReader_ptr
ParallelogramTrack::TrackDataDataReader::_unchecked_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataDataReader::_duplicate (
      dynamic_cast<TrackDataDataReader_ptr> (_tao_objref));
}

ParallelogramTrack::TrackDataDataReader_ptr
ParallelogramTrack::TrackDataDataReader::_nil ()
{
  return nullptr;
}

ParallelogramTrack::TrackDataDataReader_ptr
ParallelogramTrack::TrackDataDataReader::_duplicate (TrackDataDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
ParallelogramTrack::TrackDataDataReader::_tao_release (TrackDataDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
ParallelogramTrack::TrackDataDataReader::_is_a (const char *value)
{
  if (
      std::strcmp (value, "IDL:DDS/Entity:1.0") == 0 ||
      std::strcmp (value, "IDL:DDS/DataReader:1.0") == 0 ||
      std::strcmp (value, "IDL:OpenDDS/DCPS/DataReaderEx:1.0") == 0 ||
      std::strcmp (value, "IDL:ParallelogramTrack/TrackDataDataReader:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/LocalObject:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
      )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* ParallelogramTrack::TrackDataDataReader::_interface_repository_id () const
{
  return "IDL:ParallelogramTrack/TrackDataDataReader:1.0";
}

::CORBA::Boolean
ParallelogramTrack::TrackDataDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

