// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v4.0.0
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:372


#include "RhombusTrackTypeSupportC.h"
#include "tao/CDR.h"
#include "cstring"
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for RhombusTrack::TrackDataTypeSupport.

RhombusTrack::TrackDataTypeSupport_ptr
TAO::Objref_Traits<RhombusTrack::TrackDataTypeSupport>::duplicate (RhombusTrack::TrackDataTypeSupport_ptr p)
{
  return RhombusTrack::TrackDataTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<RhombusTrack::TrackDataTypeSupport>::release (RhombusTrack::TrackDataTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

RhombusTrack::TrackDataTypeSupport_ptr
TAO::Objref_Traits<RhombusTrack::TrackDataTypeSupport>::nil ()
{
  return RhombusTrack::TrackDataTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<RhombusTrack::TrackDataTypeSupport>::marshal (const RhombusTrack::TrackDataTypeSupport_ptr p,TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



RhombusTrack::TrackDataTypeSupport::TrackDataTypeSupport ()
{}RhombusTrack::TrackDataTypeSupport_ptr
RhombusTrack::TrackDataTypeSupport::_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataTypeSupport::_duplicate (
      dynamic_cast<TrackDataTypeSupport_ptr> (_tao_objref));
}

RhombusTrack::TrackDataTypeSupport_ptr
RhombusTrack::TrackDataTypeSupport::_unchecked_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataTypeSupport::_duplicate (
      dynamic_cast<TrackDataTypeSupport_ptr> (_tao_objref));
}

RhombusTrack::TrackDataTypeSupport_ptr
RhombusTrack::TrackDataTypeSupport::_nil ()
{
  return nullptr;
}

RhombusTrack::TrackDataTypeSupport_ptr
RhombusTrack::TrackDataTypeSupport::_duplicate (TrackDataTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
RhombusTrack::TrackDataTypeSupport::_tao_release (TrackDataTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
RhombusTrack::TrackDataTypeSupport::_is_a (const char *value)
{
  if (
      std::strcmp (value, "IDL:DDS/TypeSupport:1.0") == 0 ||
      std::strcmp (value, "IDL:OpenDDS/DCPS/TypeSupport:1.0") == 0 ||
      std::strcmp (value, "IDL:RhombusTrack/TrackDataTypeSupport:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/LocalObject:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
      )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* RhombusTrack::TrackDataTypeSupport::_interface_repository_id () const
{
  return "IDL:RhombusTrack/TrackDataTypeSupport:1.0";
}

::CORBA::Boolean
RhombusTrack::TrackDataTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for RhombusTrack::TrackDataDataWriter.

RhombusTrack::TrackDataDataWriter_ptr
TAO::Objref_Traits<RhombusTrack::TrackDataDataWriter>::duplicate (RhombusTrack::TrackDataDataWriter_ptr p)
{
  return RhombusTrack::TrackDataDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<RhombusTrack::TrackDataDataWriter>::release (RhombusTrack::TrackDataDataWriter_ptr p)
{
  ::CORBA::release (p);
}

RhombusTrack::TrackDataDataWriter_ptr
TAO::Objref_Traits<RhombusTrack::TrackDataDataWriter>::nil ()
{
  return RhombusTrack::TrackDataDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<RhombusTrack::TrackDataDataWriter>::marshal (const RhombusTrack::TrackDataDataWriter_ptr p,TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



RhombusTrack::TrackDataDataWriter::TrackDataDataWriter ()
{}RhombusTrack::TrackDataDataWriter_ptr
RhombusTrack::TrackDataDataWriter::_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataDataWriter::_duplicate (
      dynamic_cast<TrackDataDataWriter_ptr> (_tao_objref));
}

RhombusTrack::TrackDataDataWriter_ptr
RhombusTrack::TrackDataDataWriter::_unchecked_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataDataWriter::_duplicate (
      dynamic_cast<TrackDataDataWriter_ptr> (_tao_objref));
}

RhombusTrack::TrackDataDataWriter_ptr
RhombusTrack::TrackDataDataWriter::_nil ()
{
  return nullptr;
}

RhombusTrack::TrackDataDataWriter_ptr
RhombusTrack::TrackDataDataWriter::_duplicate (TrackDataDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
RhombusTrack::TrackDataDataWriter::_tao_release (TrackDataDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
RhombusTrack::TrackDataDataWriter::_is_a (const char *value)
{
  if (
      std::strcmp (value, "IDL:DDS/Entity:1.0") == 0 ||
      std::strcmp (value, "IDL:DDS/DataWriter:1.0") == 0 ||
      std::strcmp (value, "IDL:RhombusTrack/TrackDataDataWriter:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/LocalObject:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
      )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* RhombusTrack::TrackDataDataWriter::_interface_repository_id () const
{
  return "IDL:RhombusTrack/TrackDataDataWriter:1.0";
}

::CORBA::Boolean
RhombusTrack::TrackDataDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for RhombusTrack::TrackDataDataReader.

RhombusTrack::TrackDataDataReader_ptr
TAO::Objref_Traits<RhombusTrack::TrackDataDataReader>::duplicate (RhombusTrack::TrackDataDataReader_ptr p)
{
  return RhombusTrack::TrackDataDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<RhombusTrack::TrackDataDataReader>::release (RhombusTrack::TrackDataDataReader_ptr p)
{
  ::CORBA::release (p);
}

RhombusTrack::TrackDataDataReader_ptr
TAO::Objref_Traits<RhombusTrack::TrackDataDataReader>::nil ()
{
  return RhombusTrack::TrackDataDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<RhombusTrack::TrackDataDataReader>::marshal (const RhombusTrack::TrackDataDataReader_ptr p,TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



RhombusTrack::TrackDataDataReader::TrackDataDataReader ()
{}RhombusTrack::TrackDataDataReader_ptr
RhombusTrack::TrackDataDataReader::_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataDataReader::_duplicate (
      dynamic_cast<TrackDataDataReader_ptr> (_tao_objref));
}

RhombusTrack::TrackDataDataReader_ptr
RhombusTrack::TrackDataDataReader::_unchecked_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataDataReader::_duplicate (
      dynamic_cast<TrackDataDataReader_ptr> (_tao_objref));
}

RhombusTrack::TrackDataDataReader_ptr
RhombusTrack::TrackDataDataReader::_nil ()
{
  return nullptr;
}

RhombusTrack::TrackDataDataReader_ptr
RhombusTrack::TrackDataDataReader::_duplicate (TrackDataDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
RhombusTrack::TrackDataDataReader::_tao_release (TrackDataDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
RhombusTrack::TrackDataDataReader::_is_a (const char *value)
{
  if (
      std::strcmp (value, "IDL:DDS/Entity:1.0") == 0 ||
      std::strcmp (value, "IDL:DDS/DataReader:1.0") == 0 ||
      std::strcmp (value, "IDL:OpenDDS/DCPS/DataReaderEx:1.0") == 0 ||
      std::strcmp (value, "IDL:RhombusTrack/TrackDataDataReader:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/LocalObject:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
      )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* RhombusTrack::TrackDataDataReader::_interface_repository_id () const
{
  return "IDL:RhombusTrack/TrackDataDataReader:1.0";
}

::CORBA::Boolean
RhombusTrack::TrackDataDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

