// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v4.0.0
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:148

#ifndef _TAO_IDL_RADARCOMMANDTYPESUPPORTC_GQXEDL_H_
#define _TAO_IDL_RADARCOMMANDTYPESUPPORTC_GQXEDL_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types_IDLv4.h"
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

namespace CORBA
{
  using namespace IDLv4;
}

TAO_END_VERSIONED_NAMESPACE_DECL

#include "tao/ORB_Constants.h"
#include "dds/DCPS/ZeroCopyInfoSeq_T.h"
#include "dds/DCPS/ZeroCopySeq_T.h"
#include "tao/Object.h"
#include "tao/String_Manager_T.h"
#include "tao/Sequence_T.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include "tao/Object_Argument_T.h"
#include "tao/UB_String_Arguments.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "RadarCommandC.h"
#include "dds/DdsDcpsInfrastructureC.h"
#include "dds/DdsDcpsPublicationC.h"
#include "dds/DdsDcpsSubscriptionExtC.h"
#include "dds/DdsDcpsTopicC.h"
#include "dds/DdsDcpsTypeSupportExtC.h"
#include "dds/DdsDynamicDataC.h"

#if TAO_MAJOR_VERSION != 4 || TAO_MINOR_VERSION != 0 || TAO_MICRO_VERSION != 0
#error This file should be regenerated with TAO_IDL
#endif
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_module/module_ch.cpp:34

namespace RadarCommand
{

  
  // TAO_IDL - Generated from
  // /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_sequence/sequence_ch.cpp:98

  

  typedef ::TAO::DCPS::ZeroCopyDataSeq< RadarCommand::Command, DCPS_ZERO_COPY_SEQ_DEFAULT_SIZE> CommandSeq;
  
  // TAO_IDL - Generated from
  // /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_interface.cpp:742

  

#if !defined (_RADARCOMMAND_COMMANDTYPESUPPORT__VAR_OUT_CH_)
#define _RADARCOMMAND_COMMANDTYPESUPPORT__VAR_OUT_CH_

  class CommandTypeSupport;
  using CommandTypeSupport_ptr = CommandTypeSupport*;
  using CommandTypeSupport_var = TAO_Objref_Var_T<CommandTypeSupport>;
  using CommandTypeSupport_out = TAO_Objref_Out_T<CommandTypeSupport>;

#endif /* end #if !defined */

  
  // TAO_IDL - Generated from
  // /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:39

  

  class  CommandTypeSupport
    : public virtual ::OpenDDS::DCPS::TypeSupport
  
  {
  public:
    // TAO_IDL - Generated from
    // /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:297

    using _ptr_type = CommandTypeSupport_ptr;
    using _var_type = CommandTypeSupport_var;
    using _out_type = CommandTypeSupport_out;

    // The static operations.
    static CommandTypeSupport_ptr _duplicate (CommandTypeSupport_ptr obj);

    static void _tao_release (CommandTypeSupport_ptr obj);

    static CommandTypeSupport_ptr _narrow (::CORBA::Object_ptr obj);
    static CommandTypeSupport_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static CommandTypeSupport_ptr _nil ();

    virtual ::DDS::ReturnCode_t create_sample_rc (
      ::RadarCommand::Command & dst,
      ::DDS::DynamicData_ptr src) = 0;

    virtual ::RadarCommand::Command * create_sample (
      ::DDS::DynamicData_ptr src) = 0;

    virtual ::DDS::ReturnCode_t create_dynamic_sample_rc (
      ::DDS::DynamicData_ptr & dst,
      const ::RadarCommand::Command & src) = 0;

    virtual ::DDS::DynamicData_ptr create_dynamic_sample (
      const ::RadarCommand::Command & src) = 0;

    virtual ::DDS::ReturnCode_t encode_to_string (
      const ::RadarCommand::Command & sample,
      ::CORBA::String_out encoded,
      ::OpenDDS::DCPS::RepresentationFormat_ptr format) = 0;

    virtual ::DDS::ReturnCode_t encode_to_bytes (
      const ::RadarCommand::Command & sample,
      ::DDS::OctetSeq_out encoded,
      ::OpenDDS::DCPS::RepresentationFormat_ptr format) = 0;

    virtual ::DDS::ReturnCode_t decode_from_string (
      const char * encoded,
      ::RadarCommand::Command_out sample,
      ::OpenDDS::DCPS::RepresentationFormat_ptr format) = 0;

    virtual ::DDS::ReturnCode_t decode_from_bytes (
      const ::DDS::OctetSeq & encoded,
      ::RadarCommand::Command_out sample,
      ::OpenDDS::DCPS::RepresentationFormat_ptr format) = 0;

    
    // TAO_IDL - Generated from
    // /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:135

    

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id () const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    CommandTypeSupport ();

    

    virtual ~CommandTypeSupport () = default;
  
  private:
    // Private and unimplemented for concrete interfaces.
    CommandTypeSupport (const CommandTypeSupport &) = delete;
    CommandTypeSupport (CommandTypeSupport &&) = delete;
    CommandTypeSupport &operator= (const CommandTypeSupport &) = delete;
    CommandTypeSupport &operator= (CommandTypeSupport &&) = delete;
  };
  // TAO_IDL - Generated from
  // /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_interface.cpp:742

  

#if !defined (_RADARCOMMAND_COMMANDDATAWRITER__VAR_OUT_CH_)
#define _RADARCOMMAND_COMMANDDATAWRITER__VAR_OUT_CH_

  class CommandDataWriter;
  using CommandDataWriter_ptr = CommandDataWriter*;
  using CommandDataWriter_var = TAO_Objref_Var_T<CommandDataWriter>;
  using CommandDataWriter_out = TAO_Objref_Out_T<CommandDataWriter>;

#endif /* end #if !defined */

  
  // TAO_IDL - Generated from
  // /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:39

  

  class  CommandDataWriter
    : public virtual ::DDS::DataWriter
  
  {
  public:
    // TAO_IDL - Generated from
    // /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:297

    using _ptr_type = CommandDataWriter_ptr;
    using _var_type = CommandDataWriter_var;
    using _out_type = CommandDataWriter_out;

    // The static operations.
    static CommandDataWriter_ptr _duplicate (CommandDataWriter_ptr obj);

    static void _tao_release (CommandDataWriter_ptr obj);

    static CommandDataWriter_ptr _narrow (::CORBA::Object_ptr obj);
    static CommandDataWriter_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static CommandDataWriter_ptr _nil ();

    virtual ::DDS::InstanceHandle_t register_instance (
      const ::RadarCommand::Command & instance) = 0;

    virtual ::DDS::InstanceHandle_t register_instance_w_timestamp (
      const ::RadarCommand::Command & instance,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance (
      const ::RadarCommand::Command & instance,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance_w_timestamp (
      const ::RadarCommand::Command & instance,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t write (
      const ::RadarCommand::Command & instance_data,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t write_w_timestamp (
      const ::RadarCommand::Command & instance_data,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t dispose (
      const ::RadarCommand::Command & instance_data,
      ::DDS::InstanceHandle_t instance_handle) = 0;

    virtual ::DDS::ReturnCode_t dispose_w_timestamp (
      const ::RadarCommand::Command & instance_data,
      ::DDS::InstanceHandle_t instance_handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::RadarCommand::Command & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::RadarCommand::Command & instance_data) = 0;

    
    // TAO_IDL - Generated from
    // /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:135

    

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id () const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    CommandDataWriter ();

    

    virtual ~CommandDataWriter () = default;
  
  private:
    // Private and unimplemented for concrete interfaces.
    CommandDataWriter (const CommandDataWriter &) = delete;
    CommandDataWriter (CommandDataWriter &&) = delete;
    CommandDataWriter &operator= (const CommandDataWriter &) = delete;
    CommandDataWriter &operator= (CommandDataWriter &&) = delete;
  };
  // TAO_IDL - Generated from
  // /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_interface.cpp:742

  

#if !defined (_RADARCOMMAND_COMMANDDATAREADER__VAR_OUT_CH_)
#define _RADARCOMMAND_COMMANDDATAREADER__VAR_OUT_CH_

  class CommandDataReader;
  using CommandDataReader_ptr = CommandDataReader*;
  using CommandDataReader_var = TAO_Objref_Var_T<CommandDataReader>;
  using CommandDataReader_out = TAO_Objref_Out_T<CommandDataReader>;

#endif /* end #if !defined */

  
  // TAO_IDL - Generated from
  // /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:39

  

  class  CommandDataReader
    : public virtual ::OpenDDS::DCPS::DataReaderEx
  
  {
  public:
    // TAO_IDL - Generated from
    // /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:297

    using _ptr_type = CommandDataReader_ptr;
    using _var_type = CommandDataReader_var;
    using _out_type = CommandDataReader_out;

    // The static operations.
    static CommandDataReader_ptr _duplicate (CommandDataReader_ptr obj);

    static void _tao_release (CommandDataReader_ptr obj);

    static CommandDataReader_ptr _narrow (::CORBA::Object_ptr obj);
    static CommandDataReader_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static CommandDataReader_ptr _nil ();

    virtual ::DDS::ReturnCode_t read (
      ::RadarCommand::CommandSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take (
      ::RadarCommand::CommandSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_w_condition (
      ::RadarCommand::CommandSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_w_condition (
      ::RadarCommand::CommandSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_sample (
      ::RadarCommand::Command & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t take_next_sample (
      ::RadarCommand::Command & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t read_instance (
      ::RadarCommand::CommandSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_instance (
      ::RadarCommand::CommandSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_instance_w_condition (
      ::RadarCommand::CommandSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_instance_w_condition (
      ::RadarCommand::CommandSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance (
      ::RadarCommand::CommandSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance (
      ::RadarCommand::CommandSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance_w_condition (
      ::RadarCommand::CommandSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance_w_condition (
      ::RadarCommand::CommandSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t return_loan (
      ::RadarCommand::CommandSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::RadarCommand::Command & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::RadarCommand::Command & instance_data) = 0;

    
    // TAO_IDL - Generated from
    // /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:135

    

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id () const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    CommandDataReader ();

    

    virtual ~CommandDataReader () = default;
  
  private:
    // Private and unimplemented for concrete interfaces.
    CommandDataReader (const CommandDataReader &) = delete;
    CommandDataReader (CommandDataReader &&) = delete;
    CommandDataReader &operator= (const CommandDataReader &) = delete;
    CommandDataReader &operator= (CommandDataReader &&) = delete;
  };


// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_module/module_ch.cpp:62


} // module RadarCommand
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:64



TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
}

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_traits.cpp:58



TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_RADARCOMMAND_COMMANDTYPESUPPORT__TRAITS_)
#define _RADARCOMMAND_COMMANDTYPESUPPORT__TRAITS_

  template<>
  struct  Objref_Traits< ::RadarCommand::CommandTypeSupport>
  {
    static ::RadarCommand::CommandTypeSupport_ptr duplicate (::RadarCommand::CommandTypeSupport_ptr p);
    static void release (::RadarCommand::CommandTypeSupport_ptr p);
    static ::RadarCommand::CommandTypeSupport_ptr nil ();
    static ::CORBA::Boolean marshal (const ::RadarCommand::CommandTypeSupport_ptr p,TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_RADARCOMMAND_COMMANDDATAWRITER__TRAITS_)
#define _RADARCOMMAND_COMMANDDATAWRITER__TRAITS_

  template<>
  struct  Objref_Traits< ::RadarCommand::CommandDataWriter>
  {
    static ::RadarCommand::CommandDataWriter_ptr duplicate (::RadarCommand::CommandDataWriter_ptr p);
    static void release (::RadarCommand::CommandDataWriter_ptr p);
    static ::RadarCommand::CommandDataWriter_ptr nil ();
    static ::CORBA::Boolean marshal (const ::RadarCommand::CommandDataWriter_ptr p,TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_RADARCOMMAND_COMMANDDATAREADER__TRAITS_)
#define _RADARCOMMAND_COMMANDDATAREADER__TRAITS_

  template<>
  struct  Objref_Traits< ::RadarCommand::CommandDataReader>
  {
    static ::RadarCommand::CommandDataReader_ptr duplicate (::RadarCommand::CommandDataReader_ptr p);
    static void release (::RadarCommand::CommandDataReader_ptr p);
    static ::RadarCommand::CommandDataReader_ptr nil ();
    static ::CORBA::Boolean marshal (const ::RadarCommand::CommandDataReader_ptr p,TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:1648

#if defined (__ACE_INLINE__)
#include "RadarCommandTypeSupportC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

