// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v4.0.0
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:372


#include "RadarCommandTypeSupportC.h"
#include "tao/CDR.h"
#include "cstring"

#if !defined (__ACE_INLINE__)
#include "RadarCommandTypeSupportC.inl"
#endif /* !defined INLINE */
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for RadarCommand::CommandTypeSupport.

RadarCommand::CommandTypeSupport_ptr
TAO::Objref_Traits<RadarCommand::CommandTypeSupport>::duplicate (RadarCommand::CommandTypeSupport_ptr p)
{
  return RadarCommand::CommandTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<RadarCommand::CommandTypeSupport>::release (RadarCommand::CommandTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

RadarCommand::CommandTypeSupport_ptr
TAO::Objref_Traits<RadarCommand::CommandTypeSupport>::nil ()
{
  return RadarCommand::CommandTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<RadarCommand::CommandTypeSupport>::marshal (const RadarCommand::CommandTypeSupport_ptr p,TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



RadarCommand::CommandTypeSupport::CommandTypeSupport ()
{}RadarCommand::CommandTypeSupport_ptr
RadarCommand::CommandTypeSupport::_narrow (::CORBA::Object_ptr _tao_objref)
{
  return CommandTypeSupport::_duplicate (
      dynamic_cast<CommandTypeSupport_ptr> (_tao_objref));
}

RadarCommand::CommandTypeSupport_ptr
RadarCommand::CommandTypeSupport::_unchecked_narrow (::CORBA::Object_ptr _tao_objref)
{
  return CommandTypeSupport::_duplicate (
      dynamic_cast<CommandTypeSupport_ptr> (_tao_objref));
}

RadarCommand::CommandTypeSupport_ptr
RadarCommand::CommandTypeSupport::_nil ()
{
  return nullptr;
}

RadarCommand::CommandTypeSupport_ptr
RadarCommand::CommandTypeSupport::_duplicate (CommandTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
RadarCommand::CommandTypeSupport::_tao_release (CommandTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
RadarCommand::CommandTypeSupport::_is_a (const char *value)
{
  if (
      std::strcmp (value, "IDL:DDS/TypeSupport:1.0") == 0 ||
      std::strcmp (value, "IDL:OpenDDS/DCPS/TypeSupport:1.0") == 0 ||
      std::strcmp (value, "IDL:RadarCommand/CommandTypeSupport:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/LocalObject:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
      )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* RadarCommand::CommandTypeSupport::_interface_repository_id () const
{
  return "IDL:RadarCommand/CommandTypeSupport:1.0";
}

::CORBA::Boolean
RadarCommand::CommandTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for RadarCommand::CommandDataWriter.

RadarCommand::CommandDataWriter_ptr
TAO::Objref_Traits<RadarCommand::CommandDataWriter>::duplicate (RadarCommand::CommandDataWriter_ptr p)
{
  return RadarCommand::CommandDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<RadarCommand::CommandDataWriter>::release (RadarCommand::CommandDataWriter_ptr p)
{
  ::CORBA::release (p);
}

RadarCommand::CommandDataWriter_ptr
TAO::Objref_Traits<RadarCommand::CommandDataWriter>::nil ()
{
  return RadarCommand::CommandDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<RadarCommand::CommandDataWriter>::marshal (const RadarCommand::CommandDataWriter_ptr p,TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



RadarCommand::CommandDataWriter::CommandDataWriter ()
{}RadarCommand::CommandDataWriter_ptr
RadarCommand::CommandDataWriter::_narrow (::CORBA::Object_ptr _tao_objref)
{
  return CommandDataWriter::_duplicate (
      dynamic_cast<CommandDataWriter_ptr> (_tao_objref));
}

RadarCommand::CommandDataWriter_ptr
RadarCommand::CommandDataWriter::_unchecked_narrow (::CORBA::Object_ptr _tao_objref)
{
  return CommandDataWriter::_duplicate (
      dynamic_cast<CommandDataWriter_ptr> (_tao_objref));
}

RadarCommand::CommandDataWriter_ptr
RadarCommand::CommandDataWriter::_nil ()
{
  return nullptr;
}

RadarCommand::CommandDataWriter_ptr
RadarCommand::CommandDataWriter::_duplicate (CommandDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
RadarCommand::CommandDataWriter::_tao_release (CommandDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
RadarCommand::CommandDataWriter::_is_a (const char *value)
{
  if (
      std::strcmp (value, "IDL:DDS/Entity:1.0") == 0 ||
      std::strcmp (value, "IDL:DDS/DataWriter:1.0") == 0 ||
      std::strcmp (value, "IDL:RadarCommand/CommandDataWriter:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/LocalObject:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
      )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* RadarCommand::CommandDataWriter::_interface_repository_id () const
{
  return "IDL:RadarCommand/CommandDataWriter:1.0";
}

::CORBA::Boolean
RadarCommand::CommandDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for RadarCommand::CommandDataReader.

RadarCommand::CommandDataReader_ptr
TAO::Objref_Traits<RadarCommand::CommandDataReader>::duplicate (RadarCommand::CommandDataReader_ptr p)
{
  return RadarCommand::CommandDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<RadarCommand::CommandDataReader>::release (RadarCommand::CommandDataReader_ptr p)
{
  ::CORBA::release (p);
}

RadarCommand::CommandDataReader_ptr
TAO::Objref_Traits<RadarCommand::CommandDataReader>::nil ()
{
  return RadarCommand::CommandDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<RadarCommand::CommandDataReader>::marshal (const RadarCommand::CommandDataReader_ptr p,TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



RadarCommand::CommandDataReader::CommandDataReader ()
{}RadarCommand::CommandDataReader_ptr
RadarCommand::CommandDataReader::_narrow (::CORBA::Object_ptr _tao_objref)
{
  return CommandDataReader::_duplicate (
      dynamic_cast<CommandDataReader_ptr> (_tao_objref));
}

RadarCommand::CommandDataReader_ptr
RadarCommand::CommandDataReader::_unchecked_narrow (::CORBA::Object_ptr _tao_objref)
{
  return CommandDataReader::_duplicate (
      dynamic_cast<CommandDataReader_ptr> (_tao_objref));
}

RadarCommand::CommandDataReader_ptr
RadarCommand::CommandDataReader::_nil ()
{
  return nullptr;
}

RadarCommand::CommandDataReader_ptr
RadarCommand::CommandDataReader::_duplicate (CommandDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
RadarCommand::CommandDataReader::_tao_release (CommandDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
RadarCommand::CommandDataReader::_is_a (const char *value)
{
  if (
      std::strcmp (value, "IDL:DDS/Entity:1.0") == 0 ||
      std::strcmp (value, "IDL:DDS/DataReader:1.0") == 0 ||
      std::strcmp (value, "IDL:OpenDDS/DCPS/DataReaderEx:1.0") == 0 ||
      std::strcmp (value, "IDL:RadarCommand/CommandDataReader:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/LocalObject:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
      )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* RadarCommand::CommandDataReader::_interface_repository_id () const
{
  return "IDL:RadarCommand/CommandDataReader:1.0";
}

::CORBA::Boolean
RadarCommand::CommandDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

