/**
 * Auto-generated by Universal IDL Compiler
 * Source: RadarTrack.idl
 */

import { CDRReader } from '../utils/CDRReader';

export interface TrackData {
  trackId: number;
  lat: number;
  lon: number;
  speed: number;
  timestamp: number;
  classification: number;
}

export class TrackDataCodec {
  static decode(reader: CDRReader): TrackData {
    return {
      trackId: reader.readInt32(),
      lat: reader.readFloat64(),
      lon: reader.readFloat64(),
      speed: reader.readFloat32(),
      timestamp: reader.Number(reader.readInt64()),
      classification: reader.readUint8(),
    };
  }
}

