/**
 * Auto-generated by Universal IDL Compiler
 * Source: RadarTrack.idl
 */

export interface TrackData {
  trackId: number;
  lat: number;
  lon: number;
  speed: number;
  timestamp: number;
  classification: number;
  commandReceivedAt: number;
}

