// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v4.0.0
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:372


#include "PentagonTrackTypeSupportC.h"
#include "tao/CDR.h"
#include "cstring"
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for PentagonTrack::TrackDataTypeSupport.

PentagonTrack::TrackDataTypeSupport_ptr
TAO::Objref_Traits<PentagonTrack::TrackDataTypeSupport>::duplicate (PentagonTrack::TrackDataTypeSupport_ptr p)
{
  return PentagonTrack::TrackDataTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<PentagonTrack::TrackDataTypeSupport>::release (PentagonTrack::TrackDataTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

PentagonTrack::TrackDataTypeSupport_ptr
TAO::Objref_Traits<PentagonTrack::TrackDataTypeSupport>::nil ()
{
  return PentagonTrack::TrackDataTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<PentagonTrack::TrackDataTypeSupport>::marshal (const PentagonTrack::TrackDataTypeSupport_ptr p,TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



PentagonTrack::TrackDataTypeSupport::TrackDataTypeSupport ()
{}PentagonTrack::TrackDataTypeSupport_ptr
PentagonTrack::TrackDataTypeSupport::_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataTypeSupport::_duplicate (
      dynamic_cast<TrackDataTypeSupport_ptr> (_tao_objref));
}

PentagonTrack::TrackDataTypeSupport_ptr
PentagonTrack::TrackDataTypeSupport::_unchecked_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataTypeSupport::_duplicate (
      dynamic_cast<TrackDataTypeSupport_ptr> (_tao_objref));
}

PentagonTrack::TrackDataTypeSupport_ptr
PentagonTrack::TrackDataTypeSupport::_nil ()
{
  return nullptr;
}

PentagonTrack::TrackDataTypeSupport_ptr
PentagonTrack::TrackDataTypeSupport::_duplicate (TrackDataTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
PentagonTrack::TrackDataTypeSupport::_tao_release (TrackDataTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
PentagonTrack::TrackDataTypeSupport::_is_a (const char *value)
{
  if (
      std::strcmp (value, "IDL:DDS/TypeSupport:1.0") == 0 ||
      std::strcmp (value, "IDL:OpenDDS/DCPS/TypeSupport:1.0") == 0 ||
      std::strcmp (value, "IDL:PentagonTrack/TrackDataTypeSupport:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/LocalObject:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
      )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* PentagonTrack::TrackDataTypeSupport::_interface_repository_id () const
{
  return "IDL:PentagonTrack/TrackDataTypeSupport:1.0";
}

::CORBA::Boolean
PentagonTrack::TrackDataTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for PentagonTrack::TrackDataDataWriter.

PentagonTrack::TrackDataDataWriter_ptr
TAO::Objref_Traits<PentagonTrack::TrackDataDataWriter>::duplicate (PentagonTrack::TrackDataDataWriter_ptr p)
{
  return PentagonTrack::TrackDataDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<PentagonTrack::TrackDataDataWriter>::release (PentagonTrack::TrackDataDataWriter_ptr p)
{
  ::CORBA::release (p);
}

PentagonTrack::TrackDataDataWriter_ptr
TAO::Objref_Traits<PentagonTrack::TrackDataDataWriter>::nil ()
{
  return PentagonTrack::TrackDataDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<PentagonTrack::TrackDataDataWriter>::marshal (const PentagonTrack::TrackDataDataWriter_ptr p,TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



PentagonTrack::TrackDataDataWriter::TrackDataDataWriter ()
{}PentagonTrack::TrackDataDataWriter_ptr
PentagonTrack::TrackDataDataWriter::_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataDataWriter::_duplicate (
      dynamic_cast<TrackDataDataWriter_ptr> (_tao_objref));
}

PentagonTrack::TrackDataDataWriter_ptr
PentagonTrack::TrackDataDataWriter::_unchecked_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataDataWriter::_duplicate (
      dynamic_cast<TrackDataDataWriter_ptr> (_tao_objref));
}

PentagonTrack::TrackDataDataWriter_ptr
PentagonTrack::TrackDataDataWriter::_nil ()
{
  return nullptr;
}

PentagonTrack::TrackDataDataWriter_ptr
PentagonTrack::TrackDataDataWriter::_duplicate (TrackDataDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
PentagonTrack::TrackDataDataWriter::_tao_release (TrackDataDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
PentagonTrack::TrackDataDataWriter::_is_a (const char *value)
{
  if (
      std::strcmp (value, "IDL:DDS/Entity:1.0") == 0 ||
      std::strcmp (value, "IDL:DDS/DataWriter:1.0") == 0 ||
      std::strcmp (value, "IDL:PentagonTrack/TrackDataDataWriter:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/LocalObject:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
      )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* PentagonTrack::TrackDataDataWriter::_interface_repository_id () const
{
  return "IDL:PentagonTrack/TrackDataDataWriter:1.0";
}

::CORBA::Boolean
PentagonTrack::TrackDataDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for PentagonTrack::TrackDataDataReader.

PentagonTrack::TrackDataDataReader_ptr
TAO::Objref_Traits<PentagonTrack::TrackDataDataReader>::duplicate (PentagonTrack::TrackDataDataReader_ptr p)
{
  return PentagonTrack::TrackDataDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<PentagonTrack::TrackDataDataReader>::release (PentagonTrack::TrackDataDataReader_ptr p)
{
  ::CORBA::release (p);
}

PentagonTrack::TrackDataDataReader_ptr
TAO::Objref_Traits<PentagonTrack::TrackDataDataReader>::nil ()
{
  return PentagonTrack::TrackDataDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<PentagonTrack::TrackDataDataReader>::marshal (const PentagonTrack::TrackDataDataReader_ptr p,TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



PentagonTrack::TrackDataDataReader::TrackDataDataReader ()
{}PentagonTrack::TrackDataDataReader_ptr
PentagonTrack::TrackDataDataReader::_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataDataReader::_duplicate (
      dynamic_cast<TrackDataDataReader_ptr> (_tao_objref));
}

PentagonTrack::TrackDataDataReader_ptr
PentagonTrack::TrackDataDataReader::_unchecked_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataDataReader::_duplicate (
      dynamic_cast<TrackDataDataReader_ptr> (_tao_objref));
}

PentagonTrack::TrackDataDataReader_ptr
PentagonTrack::TrackDataDataReader::_nil ()
{
  return nullptr;
}

PentagonTrack::TrackDataDataReader_ptr
PentagonTrack::TrackDataDataReader::_duplicate (TrackDataDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
PentagonTrack::TrackDataDataReader::_tao_release (TrackDataDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
PentagonTrack::TrackDataDataReader::_is_a (const char *value)
{
  if (
      std::strcmp (value, "IDL:DDS/Entity:1.0") == 0 ||
      std::strcmp (value, "IDL:DDS/DataReader:1.0") == 0 ||
      std::strcmp (value, "IDL:OpenDDS/DCPS/DataReaderEx:1.0") == 0 ||
      std::strcmp (value, "IDL:PentagonTrack/TrackDataDataReader:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/LocalObject:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
      )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* PentagonTrack::TrackDataDataReader::_interface_repository_id () const
{
  return "IDL:PentagonTrack/TrackDataDataReader:1.0";
}

::CORBA::Boolean
PentagonTrack::TrackDataDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

