// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v4.0.0
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:372


#include "HexagonTrackTypeSupportC.h"
#include "tao/CDR.h"
#include "cstring"
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for HexagonTrack::TrackDataTypeSupport.

HexagonTrack::TrackDataTypeSupport_ptr
TAO::Objref_Traits<HexagonTrack::TrackDataTypeSupport>::duplicate (HexagonTrack::TrackDataTypeSupport_ptr p)
{
  return HexagonTrack::TrackDataTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<HexagonTrack::TrackDataTypeSupport>::release (HexagonTrack::TrackDataTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

HexagonTrack::TrackDataTypeSupport_ptr
TAO::Objref_Traits<HexagonTrack::TrackDataTypeSupport>::nil ()
{
  return HexagonTrack::TrackDataTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<HexagonTrack::TrackDataTypeSupport>::marshal (const HexagonTrack::TrackDataTypeSupport_ptr p,TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



HexagonTrack::TrackDataTypeSupport::TrackDataTypeSupport ()
{}HexagonTrack::TrackDataTypeSupport_ptr
HexagonTrack::TrackDataTypeSupport::_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataTypeSupport::_duplicate (
      dynamic_cast<TrackDataTypeSupport_ptr> (_tao_objref));
}

HexagonTrack::TrackDataTypeSupport_ptr
HexagonTrack::TrackDataTypeSupport::_unchecked_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataTypeSupport::_duplicate (
      dynamic_cast<TrackDataTypeSupport_ptr> (_tao_objref));
}

HexagonTrack::TrackDataTypeSupport_ptr
HexagonTrack::TrackDataTypeSupport::_nil ()
{
  return nullptr;
}

HexagonTrack::TrackDataTypeSupport_ptr
HexagonTrack::TrackDataTypeSupport::_duplicate (TrackDataTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
HexagonTrack::TrackDataTypeSupport::_tao_release (TrackDataTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
HexagonTrack::TrackDataTypeSupport::_is_a (const char *value)
{
  if (
      std::strcmp (value, "IDL:DDS/TypeSupport:1.0") == 0 ||
      std::strcmp (value, "IDL:OpenDDS/DCPS/TypeSupport:1.0") == 0 ||
      std::strcmp (value, "IDL:HexagonTrack/TrackDataTypeSupport:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/LocalObject:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
      )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* HexagonTrack::TrackDataTypeSupport::_interface_repository_id () const
{
  return "IDL:HexagonTrack/TrackDataTypeSupport:1.0";
}

::CORBA::Boolean
HexagonTrack::TrackDataTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for HexagonTrack::TrackDataDataWriter.

HexagonTrack::TrackDataDataWriter_ptr
TAO::Objref_Traits<HexagonTrack::TrackDataDataWriter>::duplicate (HexagonTrack::TrackDataDataWriter_ptr p)
{
  return HexagonTrack::TrackDataDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<HexagonTrack::TrackDataDataWriter>::release (HexagonTrack::TrackDataDataWriter_ptr p)
{
  ::CORBA::release (p);
}

HexagonTrack::TrackDataDataWriter_ptr
TAO::Objref_Traits<HexagonTrack::TrackDataDataWriter>::nil ()
{
  return HexagonTrack::TrackDataDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<HexagonTrack::TrackDataDataWriter>::marshal (const HexagonTrack::TrackDataDataWriter_ptr p,TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



HexagonTrack::TrackDataDataWriter::TrackDataDataWriter ()
{}HexagonTrack::TrackDataDataWriter_ptr
HexagonTrack::TrackDataDataWriter::_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataDataWriter::_duplicate (
      dynamic_cast<TrackDataDataWriter_ptr> (_tao_objref));
}

HexagonTrack::TrackDataDataWriter_ptr
HexagonTrack::TrackDataDataWriter::_unchecked_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataDataWriter::_duplicate (
      dynamic_cast<TrackDataDataWriter_ptr> (_tao_objref));
}

HexagonTrack::TrackDataDataWriter_ptr
HexagonTrack::TrackDataDataWriter::_nil ()
{
  return nullptr;
}

HexagonTrack::TrackDataDataWriter_ptr
HexagonTrack::TrackDataDataWriter::_duplicate (TrackDataDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
HexagonTrack::TrackDataDataWriter::_tao_release (TrackDataDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
HexagonTrack::TrackDataDataWriter::_is_a (const char *value)
{
  if (
      std::strcmp (value, "IDL:DDS/Entity:1.0") == 0 ||
      std::strcmp (value, "IDL:DDS/DataWriter:1.0") == 0 ||
      std::strcmp (value, "IDL:HexagonTrack/TrackDataDataWriter:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/LocalObject:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
      )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* HexagonTrack::TrackDataDataWriter::_interface_repository_id () const
{
  return "IDL:HexagonTrack/TrackDataDataWriter:1.0";
}

::CORBA::Boolean
HexagonTrack::TrackDataDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for HexagonTrack::TrackDataDataReader.

HexagonTrack::TrackDataDataReader_ptr
TAO::Objref_Traits<HexagonTrack::TrackDataDataReader>::duplicate (HexagonTrack::TrackDataDataReader_ptr p)
{
  return HexagonTrack::TrackDataDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<HexagonTrack::TrackDataDataReader>::release (HexagonTrack::TrackDataDataReader_ptr p)
{
  ::CORBA::release (p);
}

HexagonTrack::TrackDataDataReader_ptr
TAO::Objref_Traits<HexagonTrack::TrackDataDataReader>::nil ()
{
  return HexagonTrack::TrackDataDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<HexagonTrack::TrackDataDataReader>::marshal (const HexagonTrack::TrackDataDataReader_ptr p,TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



HexagonTrack::TrackDataDataReader::TrackDataDataReader ()
{}HexagonTrack::TrackDataDataReader_ptr
HexagonTrack::TrackDataDataReader::_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataDataReader::_duplicate (
      dynamic_cast<TrackDataDataReader_ptr> (_tao_objref));
}

HexagonTrack::TrackDataDataReader_ptr
HexagonTrack::TrackDataDataReader::_unchecked_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataDataReader::_duplicate (
      dynamic_cast<TrackDataDataReader_ptr> (_tao_objref));
}

HexagonTrack::TrackDataDataReader_ptr
HexagonTrack::TrackDataDataReader::_nil ()
{
  return nullptr;
}

HexagonTrack::TrackDataDataReader_ptr
HexagonTrack::TrackDataDataReader::_duplicate (TrackDataDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
HexagonTrack::TrackDataDataReader::_tao_release (TrackDataDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
HexagonTrack::TrackDataDataReader::_is_a (const char *value)
{
  if (
      std::strcmp (value, "IDL:DDS/Entity:1.0") == 0 ||
      std::strcmp (value, "IDL:DDS/DataReader:1.0") == 0 ||
      std::strcmp (value, "IDL:OpenDDS/DCPS/DataReaderEx:1.0") == 0 ||
      std::strcmp (value, "IDL:HexagonTrack/TrackDataDataReader:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/LocalObject:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
      )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* HexagonTrack::TrackDataDataReader::_interface_repository_id () const
{
  return "IDL:HexagonTrack/TrackDataDataReader:1.0";
}

::CORBA::Boolean
HexagonTrack::TrackDataDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

