// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v4.0.0
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:372


#include "RadarTrackTypeSupportC.h"
#include "tao/CDR.h"
#include "cstring"

#if !defined (__ACE_INLINE__)
#include "RadarTrackTypeSupportC.inl"
#endif /* !defined INLINE */
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for RadarTrack::TrackDataTypeSupport.

RadarTrack::TrackDataTypeSupport_ptr
TAO::Objref_Traits<RadarTrack::TrackDataTypeSupport>::duplicate (RadarTrack::TrackDataTypeSupport_ptr p)
{
  return RadarTrack::TrackDataTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<RadarTrack::TrackDataTypeSupport>::release (RadarTrack::TrackDataTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

RadarTrack::TrackDataTypeSupport_ptr
TAO::Objref_Traits<RadarTrack::TrackDataTypeSupport>::nil ()
{
  return RadarTrack::TrackDataTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<RadarTrack::TrackDataTypeSupport>::marshal (const RadarTrack::TrackDataTypeSupport_ptr p,TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



RadarTrack::TrackDataTypeSupport::TrackDataTypeSupport ()
{}RadarTrack::TrackDataTypeSupport_ptr
RadarTrack::TrackDataTypeSupport::_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataTypeSupport::_duplicate (
      dynamic_cast<TrackDataTypeSupport_ptr> (_tao_objref));
}

RadarTrack::TrackDataTypeSupport_ptr
RadarTrack::TrackDataTypeSupport::_unchecked_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataTypeSupport::_duplicate (
      dynamic_cast<TrackDataTypeSupport_ptr> (_tao_objref));
}

RadarTrack::TrackDataTypeSupport_ptr
RadarTrack::TrackDataTypeSupport::_nil ()
{
  return nullptr;
}

RadarTrack::TrackDataTypeSupport_ptr
RadarTrack::TrackDataTypeSupport::_duplicate (TrackDataTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
RadarTrack::TrackDataTypeSupport::_tao_release (TrackDataTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
RadarTrack::TrackDataTypeSupport::_is_a (const char *value)
{
  if (
      std::strcmp (value, "IDL:DDS/TypeSupport:1.0") == 0 ||
      std::strcmp (value, "IDL:OpenDDS/DCPS/TypeSupport:1.0") == 0 ||
      std::strcmp (value, "IDL:RadarTrack/TrackDataTypeSupport:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/LocalObject:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
      )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* RadarTrack::TrackDataTypeSupport::_interface_repository_id () const
{
  return "IDL:RadarTrack/TrackDataTypeSupport:1.0";
}

::CORBA::Boolean
RadarTrack::TrackDataTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for RadarTrack::TrackDataDataWriter.

RadarTrack::TrackDataDataWriter_ptr
TAO::Objref_Traits<RadarTrack::TrackDataDataWriter>::duplicate (RadarTrack::TrackDataDataWriter_ptr p)
{
  return RadarTrack::TrackDataDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<RadarTrack::TrackDataDataWriter>::release (RadarTrack::TrackDataDataWriter_ptr p)
{
  ::CORBA::release (p);
}

RadarTrack::TrackDataDataWriter_ptr
TAO::Objref_Traits<RadarTrack::TrackDataDataWriter>::nil ()
{
  return RadarTrack::TrackDataDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<RadarTrack::TrackDataDataWriter>::marshal (const RadarTrack::TrackDataDataWriter_ptr p,TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



RadarTrack::TrackDataDataWriter::TrackDataDataWriter ()
{}RadarTrack::TrackDataDataWriter_ptr
RadarTrack::TrackDataDataWriter::_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataDataWriter::_duplicate (
      dynamic_cast<TrackDataDataWriter_ptr> (_tao_objref));
}

RadarTrack::TrackDataDataWriter_ptr
RadarTrack::TrackDataDataWriter::_unchecked_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataDataWriter::_duplicate (
      dynamic_cast<TrackDataDataWriter_ptr> (_tao_objref));
}

RadarTrack::TrackDataDataWriter_ptr
RadarTrack::TrackDataDataWriter::_nil ()
{
  return nullptr;
}

RadarTrack::TrackDataDataWriter_ptr
RadarTrack::TrackDataDataWriter::_duplicate (TrackDataDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
RadarTrack::TrackDataDataWriter::_tao_release (TrackDataDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
RadarTrack::TrackDataDataWriter::_is_a (const char *value)
{
  if (
      std::strcmp (value, "IDL:DDS/Entity:1.0") == 0 ||
      std::strcmp (value, "IDL:DDS/DataWriter:1.0") == 0 ||
      std::strcmp (value, "IDL:RadarTrack/TrackDataDataWriter:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/LocalObject:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
      )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* RadarTrack::TrackDataDataWriter::_interface_repository_id () const
{
  return "IDL:RadarTrack/TrackDataDataWriter:1.0";
}

::CORBA::Boolean
RadarTrack::TrackDataDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for RadarTrack::TrackDataDataReader.

RadarTrack::TrackDataDataReader_ptr
TAO::Objref_Traits<RadarTrack::TrackDataDataReader>::duplicate (RadarTrack::TrackDataDataReader_ptr p)
{
  return RadarTrack::TrackDataDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<RadarTrack::TrackDataDataReader>::release (RadarTrack::TrackDataDataReader_ptr p)
{
  ::CORBA::release (p);
}

RadarTrack::TrackDataDataReader_ptr
TAO::Objref_Traits<RadarTrack::TrackDataDataReader>::nil ()
{
  return RadarTrack::TrackDataDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<RadarTrack::TrackDataDataReader>::marshal (const RadarTrack::TrackDataDataReader_ptr p,TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



RadarTrack::TrackDataDataReader::TrackDataDataReader ()
{}RadarTrack::TrackDataDataReader_ptr
RadarTrack::TrackDataDataReader::_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataDataReader::_duplicate (
      dynamic_cast<TrackDataDataReader_ptr> (_tao_objref));
}

RadarTrack::TrackDataDataReader_ptr
RadarTrack::TrackDataDataReader::_unchecked_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataDataReader::_duplicate (
      dynamic_cast<TrackDataDataReader_ptr> (_tao_objref));
}

RadarTrack::TrackDataDataReader_ptr
RadarTrack::TrackDataDataReader::_nil ()
{
  return nullptr;
}

RadarTrack::TrackDataDataReader_ptr
RadarTrack::TrackDataDataReader::_duplicate (TrackDataDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
RadarTrack::TrackDataDataReader::_tao_release (TrackDataDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
RadarTrack::TrackDataDataReader::_is_a (const char *value)
{
  if (
      std::strcmp (value, "IDL:DDS/Entity:1.0") == 0 ||
      std::strcmp (value, "IDL:DDS/DataReader:1.0") == 0 ||
      std::strcmp (value, "IDL:OpenDDS/DCPS/DataReaderEx:1.0") == 0 ||
      std::strcmp (value, "IDL:RadarTrack/TrackDataDataReader:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/LocalObject:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
      )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* RadarTrack::TrackDataDataReader::_interface_repository_id () const
{
  return "IDL:RadarTrack/TrackDataDataReader:1.0";
}

::CORBA::Boolean
RadarTrack::TrackDataDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

