// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v4.0.0
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:372


#include "EllipseTrackTypeSupportC.h"
#include "tao/CDR.h"
#include "cstring"

#if !defined (__ACE_INLINE__)
#include "EllipseTrackTypeSupportC.inl"
#endif /* !defined INLINE */
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for EllipseTrack::TrackDataTypeSupport.

EllipseTrack::TrackDataTypeSupport_ptr
TAO::Objref_Traits<EllipseTrack::TrackDataTypeSupport>::duplicate (EllipseTrack::TrackDataTypeSupport_ptr p)
{
  return EllipseTrack::TrackDataTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<EllipseTrack::TrackDataTypeSupport>::release (EllipseTrack::TrackDataTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

EllipseTrack::TrackDataTypeSupport_ptr
TAO::Objref_Traits<EllipseTrack::TrackDataTypeSupport>::nil ()
{
  return EllipseTrack::TrackDataTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<EllipseTrack::TrackDataTypeSupport>::marshal (const EllipseTrack::TrackDataTypeSupport_ptr p,TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



EllipseTrack::TrackDataTypeSupport::TrackDataTypeSupport ()
{}EllipseTrack::TrackDataTypeSupport_ptr
EllipseTrack::TrackDataTypeSupport::_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataTypeSupport::_duplicate (
      dynamic_cast<TrackDataTypeSupport_ptr> (_tao_objref));
}

EllipseTrack::TrackDataTypeSupport_ptr
EllipseTrack::TrackDataTypeSupport::_unchecked_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataTypeSupport::_duplicate (
      dynamic_cast<TrackDataTypeSupport_ptr> (_tao_objref));
}

EllipseTrack::TrackDataTypeSupport_ptr
EllipseTrack::TrackDataTypeSupport::_nil ()
{
  return nullptr;
}

EllipseTrack::TrackDataTypeSupport_ptr
EllipseTrack::TrackDataTypeSupport::_duplicate (TrackDataTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
EllipseTrack::TrackDataTypeSupport::_tao_release (TrackDataTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
EllipseTrack::TrackDataTypeSupport::_is_a (const char *value)
{
  if (
      std::strcmp (value, "IDL:DDS/TypeSupport:1.0") == 0 ||
      std::strcmp (value, "IDL:OpenDDS/DCPS/TypeSupport:1.0") == 0 ||
      std::strcmp (value, "IDL:EllipseTrack/TrackDataTypeSupport:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/LocalObject:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
      )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* EllipseTrack::TrackDataTypeSupport::_interface_repository_id () const
{
  return "IDL:EllipseTrack/TrackDataTypeSupport:1.0";
}

::CORBA::Boolean
EllipseTrack::TrackDataTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for EllipseTrack::TrackDataDataWriter.

EllipseTrack::TrackDataDataWriter_ptr
TAO::Objref_Traits<EllipseTrack::TrackDataDataWriter>::duplicate (EllipseTrack::TrackDataDataWriter_ptr p)
{
  return EllipseTrack::TrackDataDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<EllipseTrack::TrackDataDataWriter>::release (EllipseTrack::TrackDataDataWriter_ptr p)
{
  ::CORBA::release (p);
}

EllipseTrack::TrackDataDataWriter_ptr
TAO::Objref_Traits<EllipseTrack::TrackDataDataWriter>::nil ()
{
  return EllipseTrack::TrackDataDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<EllipseTrack::TrackDataDataWriter>::marshal (const EllipseTrack::TrackDataDataWriter_ptr p,TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



EllipseTrack::TrackDataDataWriter::TrackDataDataWriter ()
{}EllipseTrack::TrackDataDataWriter_ptr
EllipseTrack::TrackDataDataWriter::_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataDataWriter::_duplicate (
      dynamic_cast<TrackDataDataWriter_ptr> (_tao_objref));
}

EllipseTrack::TrackDataDataWriter_ptr
EllipseTrack::TrackDataDataWriter::_unchecked_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataDataWriter::_duplicate (
      dynamic_cast<TrackDataDataWriter_ptr> (_tao_objref));
}

EllipseTrack::TrackDataDataWriter_ptr
EllipseTrack::TrackDataDataWriter::_nil ()
{
  return nullptr;
}

EllipseTrack::TrackDataDataWriter_ptr
EllipseTrack::TrackDataDataWriter::_duplicate (TrackDataDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
EllipseTrack::TrackDataDataWriter::_tao_release (TrackDataDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
EllipseTrack::TrackDataDataWriter::_is_a (const char *value)
{
  if (
      std::strcmp (value, "IDL:DDS/Entity:1.0") == 0 ||
      std::strcmp (value, "IDL:DDS/DataWriter:1.0") == 0 ||
      std::strcmp (value, "IDL:EllipseTrack/TrackDataDataWriter:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/LocalObject:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
      )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* EllipseTrack::TrackDataDataWriter::_interface_repository_id () const
{
  return "IDL:EllipseTrack/TrackDataDataWriter:1.0";
}

::CORBA::Boolean
EllipseTrack::TrackDataDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for EllipseTrack::TrackDataDataReader.

EllipseTrack::TrackDataDataReader_ptr
TAO::Objref_Traits<EllipseTrack::TrackDataDataReader>::duplicate (EllipseTrack::TrackDataDataReader_ptr p)
{
  return EllipseTrack::TrackDataDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<EllipseTrack::TrackDataDataReader>::release (EllipseTrack::TrackDataDataReader_ptr p)
{
  ::CORBA::release (p);
}

EllipseTrack::TrackDataDataReader_ptr
TAO::Objref_Traits<EllipseTrack::TrackDataDataReader>::nil ()
{
  return EllipseTrack::TrackDataDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<EllipseTrack::TrackDataDataReader>::marshal (const EllipseTrack::TrackDataDataReader_ptr p,TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



EllipseTrack::TrackDataDataReader::TrackDataDataReader ()
{}EllipseTrack::TrackDataDataReader_ptr
EllipseTrack::TrackDataDataReader::_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataDataReader::_duplicate (
      dynamic_cast<TrackDataDataReader_ptr> (_tao_objref));
}

EllipseTrack::TrackDataDataReader_ptr
EllipseTrack::TrackDataDataReader::_unchecked_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TrackDataDataReader::_duplicate (
      dynamic_cast<TrackDataDataReader_ptr> (_tao_objref));
}

EllipseTrack::TrackDataDataReader_ptr
EllipseTrack::TrackDataDataReader::_nil ()
{
  return nullptr;
}

EllipseTrack::TrackDataDataReader_ptr
EllipseTrack::TrackDataDataReader::_duplicate (TrackDataDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
EllipseTrack::TrackDataDataReader::_tao_release (TrackDataDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
EllipseTrack::TrackDataDataReader::_is_a (const char *value)
{
  if (
      std::strcmp (value, "IDL:DDS/Entity:1.0") == 0 ||
      std::strcmp (value, "IDL:DDS/DataReader:1.0") == 0 ||
      std::strcmp (value, "IDL:OpenDDS/DCPS/DataReaderEx:1.0") == 0 ||
      std::strcmp (value, "IDL:EllipseTrack/TrackDataDataReader:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/LocalObject:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
      )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* EllipseTrack::TrackDataDataReader::_interface_repository_id () const
{
  return "IDL:EllipseTrack/TrackDataDataReader:1.0";
}

::CORBA::Boolean
EllipseTrack::TrackDataDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

